"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {BarChart3,Bell,BookOpen,ClipboardList,FileUp,LayoutDashboard,Lightbulb,LogOut,Menu,MessagesSquare,Route,Settings,ShieldAlert,Target,Users,X} from "lucide-react";
import {Logo} from "./logo";
import {logout} from "@/lib/api";

const primary=[["/bank/dashboard","Dashboard",LayoutDashboard],["/bank/customers","Customer 360",Users],["/bank/conversations","Conversations",MessagesSquare],["/bank/leads","Leads",Target],["/bank/opportunities","Sales Opportunities",Lightbulb],["/bank/retention","Retention",ShieldAlert],["/bank/service-intelligence","Service Intelligence",Route],["/bank/service-requests","Service Requests",ClipboardList],["/bank/analytics","Analytics",BarChart3],["/bank/notifications","Notifications",Bell]] as const;
const admin=[["/bank/admin/knowledge","Knowledge Base / Upload PDF",FileUp],["/bank/admin/users","Users & Roles",Users],["/bank/admin/products","Products",ClipboardList],["/bank/admin/routing-rules","Routing Rules",Route],["/bank/admin/audit","Audit Logs",BookOpen],["/bank/admin/ai-settings","AI Configuration",Settings]] as const;

export function BankShell({children}:{children:React.ReactNode}){
 const path=usePathname(),[open,setOpen]=useState(false),[role,setRole]=useState<string|null>(null);
 useEffect(()=>{try{setRole(JSON.parse(localStorage.getItem("user")||"{}").role||null)}catch{setRole(null)}},[]);
 const isAdmin=role==="admin";
 const navigation=<><p className="mt-8 px-3 text-[10px] font-bold uppercase tracking-widest text-slate-400">Workspace</p><nav className="mt-2 space-y-1">{primary.map(([href,label,Icon])=><NavLink key={href} href={href} label={label} icon={Icon} active={path.startsWith(href)} close={()=>setOpen(false)}/>)}</nav>{isAdmin&&<><p className="mt-7 px-3 text-[10px] font-bold uppercase tracking-widest text-slate-400">Administration</p><nav className="mt-2 space-y-1">{admin.map(([href,label,Icon])=><NavLink key={href} href={href} label={label} icon={Icon} active={path.startsWith(href)} close={()=>setOpen(false)}/>)}</nav></>}</>;
 return <div className="min-h-screen bg-mist"><aside className="fixed inset-y-0 left-0 z-40 hidden w-72 overflow-y-auto bg-navy p-5 lg:block"><Logo light/>{navigation}<button onClick={logout} className="mt-8 flex items-center gap-2 px-3 pb-5 text-sm text-slate-300"><LogOut size={17}/>Sign out</button></aside>{open&&<div className="fixed inset-0 z-50 lg:hidden"><button aria-label="Close navigation" className="absolute inset-0 bg-slate-950/50" onClick={()=>setOpen(false)}/><aside className="relative h-full w-72 overflow-y-auto bg-navy p-5"><div className="flex items-center justify-between"><Logo light/><button className="text-white" onClick={()=>setOpen(false)}><X/></button></div>{navigation}<button onClick={logout} className="mt-8 flex items-center gap-2 px-3 text-sm text-slate-300"><LogOut size={17}/>Sign out</button></aside></div>}<main className="lg:ml-72"><header className="flex min-h-16 items-center justify-between gap-3 border-b bg-white px-4 sm:px-6"><div className="flex items-center gap-3"><button onClick={()=>setOpen(true)} className="rounded-lg border p-2 lg:hidden" aria-label="Open navigation"><Menu size={19}/></button><span className="hidden font-semibold text-navy sm:inline">Bank Intelligence Portal</span><span className="badge bg-amber-50 text-amber-700">Demo / Synthetic Data</span></div><div className="flex items-center gap-2">{isAdmin&&<Link href="/bank/admin/knowledge" className="btn-primary px-3"><FileUp size={16}/><span className="hidden sm:inline">Upload knowledge PDF</span></Link>}<Bell size={18}/><div className="grid h-9 w-9 place-items-center rounded-full bg-navy text-sm text-white">PS</div></div></header><div className="p-5 lg:p-8">{children}</div></main></div>
}

function NavLink({href,label,icon:Icon,active,close}:{href:string;label:string;icon:any;active:boolean;close:()=>void}){return <Link href={href} onClick={close} className={`flex items-center gap-3 rounded-lg px-3 py-2 text-sm ${active?"bg-white/15 text-white":"text-slate-300 hover:bg-white/5"}`}><Icon size={17}/>{label}</Link>}
