"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {CheckCircle2,ChevronLeft,ChevronRight,Filter,MessageSquareText,MessagesSquare,RotateCcw,Search,ShieldAlert,SmilePlus,Users} from "lucide-react";
import {api} from "@/lib/api";
import {VoiceSentimentAnalyzer} from "./voice-sentiment-analyzer";
type Conversation={id:number;customer_id:number;customer_code:string;customer_name:string;title:string;primary_intent:string;sentiment:string;resolution_status:string;message_count:number;updated_at:string};
const tone=(value:string)=>value.toLowerCase().replaceAll(" ","-");
export function ConversationMonitor(){
 const [sessions,setSessions]=useState<Conversation[]>([]),[query,setQuery]=useState(""),[sentiment,setSentiment]=useState(""),[resolution,setResolution]=useState(""),[error,setError]=useState(""),[page,setPage]=useState(1),[loading,setLoading]=useState(true);const pageSize=10;
 const load=()=>{setLoading(true);api<Conversation[]>("/conversations").then(setSessions).catch((e:any)=>setError(e.message)).finally(()=>setLoading(false))};useEffect(()=>{load()},[]);
 const sentiments=useMemo(()=>Array.from(new Set(sessions.map(item=>item.sentiment))).sort(),[sessions]),resolutions=useMemo(()=>Array.from(new Set(sessions.map(item=>item.resolution_status))).sort(),[sessions]);
 const visible=useMemo(()=>sessions.filter(item=>`${item.customer_name} ${item.customer_code||item.customer_id} ${item.title} ${item.primary_intent}`.toLowerCase().includes(query.toLowerCase())&&(!sentiment||item.sentiment===sentiment)&&(!resolution||item.resolution_status===resolution)),[sessions,query,sentiment,resolution]);
 const pageCount=Math.max(1,Math.ceil(visible.length/pageSize)),pageRows=visible.slice((page-1)*pageSize,page*pageSize),hasFilters=Boolean(query||sentiment||resolution),clear=()=>{setQuery("");setSentiment("");setResolution("");setPage(1)};
 const negative=sessions.filter(item=>["Negative","Highly Negative"].includes(item.sentiment)).length,resolved=sessions.filter(item=>["Answered","Resolved","Closed"].includes(item.resolution_status)).length,customers=new Set(sessions.map(item=>item.customer_id)).size;
 return <div className="conversation-monitor"><header className="monitor-head"><div className="monitor-head-icon"><MessagesSquare/></div><div><p>Engagement intelligence</p><h1>Customer conversations</h1><span>Review sessions, sentiment, resolution, and complete chat history.</span></div></header>
  <section className="monitor-kpis"><article><MessagesSquare/><span><small>Total sessions</small><b>{sessions.length}</b></span></article><article><Users/><span><small>Customers engaged</small><b>{customers}</b></span></article><article className="green"><CheckCircle2/><span><small>Resolved sessions</small><b>{resolved}</b></span></article><article className="red"><ShieldAlert/><span><small>Needs attention</small><b>{negative}</b></span></article></section>
  <div className="monitor-layout"><main><section className="monitor-filters"><header><Filter/><div><b>Filter conversations</b><p>Find a session by customer, topic, sentiment, or resolution.</p></div></header><div><label className="monitor-search"><Search/><input placeholder="Customer, ID, topic, or intent" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><select value={sentiment} onChange={e=>{setSentiment(e.target.value);setPage(1)}}><option value="">All sentiments</option>{sentiments.map(value=><option key={value}>{value}</option>)}</select><select value={resolution} onChange={e=>{setResolution(e.target.value);setPage(1)}}><option value="">All resolutions</option>{resolutions.map(value=><option key={value}>{value}</option>)}</select><button disabled={!hasFilters} onClick={clear}><RotateCcw/>Clear</button></div><footer>Showing <b>{visible.length}</b> of {sessions.length} sessions</footer></section>
   <section className="monitor-table"><header><div><MessageSquareText/><span><b>Conversation review queue</b><small>Select a session to inspect chat and sentiment.</small></span></div><i>{visible.length} sessions</i></header><div className="monitor-columns"><span>Session &amp; customer</span><span>Conversation</span><span>Intent</span><span>Sentiment</span><span>Resolution</span><span>Action</span></div>{loading?<div className="monitor-empty">Loading conversations…</div>:pageRows.length?pageRows.map(item=><article key={item.id}><div className="monitor-customer"><i>{item.customer_name?.charAt(0)||"C"}</i><span><b>{item.customer_name}</b><small>#{item.id} · {item.customer_code||item.customer_id}</small></span></div><div className="monitor-topic"><b>{item.title}</b><small>{item.message_count} messages</small></div><span className="intent">{item.primary_intent}</span><span className={`monitor-badge ${tone(item.sentiment)}`}>{item.sentiment}</span><span className={`monitor-badge resolution ${tone(item.resolution_status)}`}>{item.resolution_status}</span><Link href={`/bank/conversations/${item.id}`}>Review <ChevronRight/></Link></article>):<div className="monitor-empty"><Search/><h2>No matching sessions</h2><p>{error||"Try adjusting the selected filters."}</p></div>}<footer><span>Page {page} of {pageCount}</span><div><button disabled={page===1} onClick={()=>setPage(value=>value-1)}><ChevronLeft/></button><button disabled={page===pageCount} onClick={()=>setPage(value=>value+1)}><ChevronRight/></button></div></footer></section></main><aside className="conversation-voice"><VoiceSentimentAnalyzer onSaved={load}/><div className="voice-note"><SmilePlus/><p><b>Privacy-aware analysis</b><span>Audio is transcribed for the session and is not stored.</span></p></div></aside></div>
 </div>
}
