"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {Activity,ArrowRight,MessageSquareText,Search} from "lucide-react";
import {CartesianGrid,Line,LineChart,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {api} from "@/lib/api";

type Conversation={id:number;customer_id:number;customer_name:string;title:string;primary_intent:string;sentiment:string;resolution_status:string;message_count:number;updated_at:string};
type Interaction={analysis_id:number;conversation_id:number;customer_name:string;message:string;sentiment:string;emotion:string;score:number;intent:string;created_at:string};
const sentimentClass=(sentiment:string)=>sentiment==="Highly Negative"?"bg-red-50 text-red-700":sentiment==="Negative"?"bg-amber-50 text-amber-700":sentiment==="Positive"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-700";

export function ConversationMonitor(){
 const [sessions,setSessions]=useState<Conversation[]>([]),[recent,setRecent]=useState<Interaction[]>([]),[q,setQ]=useState(""),[error,setError]=useState("");
 useEffect(()=>{Promise.all([api<Conversation[]>("/conversations"),api<Interaction[]>("/sentiment/recent?limit=10")]).then(([conversations,interactions])=>{setSessions(conversations);setRecent(interactions)}).catch((e:any)=>setError(e.message))},[]);
 const visible=useMemo(()=>sessions.filter(item=>JSON.stringify(item).toLowerCase().includes(q.toLowerCase())),[sessions,q]);
 const chart=recent.map((item,index)=>({...item,label:`${index+1}`,shortMessage:item.message.length>45?`${item.message.slice(0,45)}…`:item.message}));
 return <><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold text-navy">Customer conversations</h1><p className="mt-1 text-slate-500">Review chats, session sentiment, and recent interaction health.</p></div><label className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input className="input pl-9" placeholder="Search sessions" value={q} onChange={e=>setQ(e.target.value)}/></label></div>
 <section className="card mt-6 p-6"><div className="flex items-center gap-2"><Activity className="text-brand"/><div><h2 className="font-bold text-navy">Last 10 customer interactions</h2><p className="text-xs text-slate-500">Sentiment score from highly negative (-0.9) through neutral (0) to positive.</p></div></div><div className="mt-5 h-72">{chart.length?<ResponsiveContainer width="100%" height="100%"><LineChart data={chart} margin={{left:0,right:20,top:10,bottom:5}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis domain={[-1,1]} ticks={[-1,-.5,0,.5,1]}/><ReferenceLine y={0} stroke="#94a3b8"/><Tooltip content={({active,payload}:any)=>active&&payload?.length?<div className="max-w-xs rounded-xl border bg-white p-3 text-xs shadow-lg"><p className="font-bold">{payload[0].payload.customer_name}</p><p className="mt-1 text-slate-500">{payload[0].payload.shortMessage}</p><p className="mt-2 font-semibold">{payload[0].payload.sentiment} • {payload[0].payload.emotion}</p></div>:null}/><Line type="monotone" dataKey="score" stroke="#d97706" strokeWidth={3} dot={{r:5}} activeDot={{r:7}}/></LineChart></ResponsiveContainer>:<div className="grid h-full place-items-center text-sm text-slate-400">No analyzed interactions yet.</div>}</div><div className="mt-4 grid gap-2 md:grid-cols-2">{recent.slice().reverse().slice(0,4).map(item=><Link href={`/bank/conversations/${item.conversation_id}`} key={item.analysis_id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm hover:bg-slate-100"><span className={`badge ${sentimentClass(item.sentiment)}`}>{item.sentiment}</span><span className="min-w-0 flex-1 truncate">{item.customer_name}: {item.message}</span><ArrowRight size={15}/></Link>)}</div></section>
 <section className="card mt-6 overflow-x-auto"><table><thead><tr>{["Session","Customer","Conversation","Intent","Sentiment","Resolution","Messages","Open chat"].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{visible.map(item=><tr key={item.id} className="hover:bg-slate-50"><td>#{item.id}</td><td className="font-semibold">{item.customer_name}</td><td className="max-w-xs"><p className="font-medium">{item.title}</p></td><td>{item.primary_intent}</td><td><span className={`badge ${sentimentClass(item.sentiment)}`}>{item.sentiment}</span></td><td>{item.resolution_status}</td><td>{item.message_count}</td><td><Link className="btn-secondary whitespace-nowrap" href={`/bank/conversations/${item.id}`}><MessageSquareText size={16}/>View chat</Link></td></tr>)}</tbody></table>{!visible.length&&<p className="p-12 text-center text-slate-500">{error||"No matching conversations."}</p>}</section></>;
}
