"use client";
import {useEffect,useState} from "react";
import {ChevronRight,Send,X} from "lucide-react";
import {api} from "@/lib/api";

type RequestRow={id:number;request_code:string;category:string;issue:string;priority:string;status:string;created_at:string};
type RequestMessage={id:number;message:string;sender_name:string;sender_type:"customer"|"employee";created_at:string};

export function CustomerServiceRequests(){
 const [rows,setRows]=useState<RequestRow[]>([]),[selected,setSelected]=useState<RequestRow|null>(null),[messages,setMessages]=useState<RequestMessage[]>([]),[message,setMessage]=useState(""),[sending,setSending]=useState(false),[error,setError]=useState("");
 useEffect(()=>{api<RequestRow[]>("/service-requests").then(setRows).catch((e:any)=>setError(e.message))},[]);
 async function open(row:RequestRow){setSelected(row);setMessage("");setError("");try{setMessages(await api<RequestMessage[]>(`/service-requests/${row.id}/messages`))}catch(e:any){setError(e.message)}}
 async function reply(){if(!selected||!message.trim())return;setSending(true);setError("");try{const added=await api<RequestMessage>(`/service-requests/${selected.id}/messages`,{method:"POST",body:JSON.stringify({message})});setMessages(items=>[...items,added]);setMessage("")}catch(e:any){setError(e.message)}finally{setSending(false)}}
 return <><h1 className="text-3xl font-bold text-navy">Service requests</h1><p className="mt-2 text-slate-500">Track progress and communicate securely with the bank.</p><div className="mt-7 grid gap-4">{rows.map(row=><button key={row.id} onClick={()=>open(row)} className="card flex w-full items-center gap-4 p-5 text-left hover:border-navy"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-bold text-navy">{row.request_code}</p><span className="badge bg-blue-50 text-blue-700">{row.status}</span><span className={`badge ${row.priority==="High"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}>{row.priority}</span></div><p className="mt-2 font-medium">{row.category}</p><p className="mt-1 truncate text-sm text-slate-500">{row.issue}</p></div><ChevronRight className="text-slate-400"/></button>)}{!rows.length&&!error&&<div className="card p-12 text-center text-slate-500">No service requests yet.</div>}{error&&<p className="text-sm text-red-600">{error}</p>}</div>
 {selected&&<div className="fixed inset-0 z-50 flex justify-end bg-slate-950/30" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><section className="flex h-full w-full max-w-xl flex-col bg-white shadow-2xl"><header className="flex items-start justify-between border-b p-6"><div><p className="text-xs font-semibold uppercase tracking-wide text-brand">{selected.request_code}</p><h2 className="mt-1 text-2xl font-bold text-navy">{selected.category}</h2><p className="mt-2 text-sm text-slate-500">Status: <strong>{selected.status}</strong> • Priority: {selected.priority}</p></div><button className="rounded-lg p-2 hover:bg-slate-100" onClick={()=>setSelected(null)} aria-label="Close"><X/></button></header><div className="flex-1 space-y-3 overflow-y-auto p-6"><div className="rounded-xl border bg-slate-50 p-4 text-sm"><p className="text-xs font-semibold text-slate-400">ORIGINAL REQUEST</p><p className="mt-2 leading-6">{selected.issue}</p></div>{messages.map(item=><div key={item.id} className={`max-w-[85%] rounded-xl p-3 ${item.sender_type==="customer"?"ml-auto bg-navy text-white":"bg-slate-100"}`}><p className="text-sm leading-6">{item.message}</p><p className={`mt-2 text-xs ${item.sender_type==="customer"?"text-slate-300":"text-slate-400"}`}>{item.sender_name} • {new Date(item.created_at).toLocaleString()}</p></div>)}{!messages.length&&<p className="py-5 text-center text-sm text-slate-400">No follow-up messages yet.</p>}</div><div className="border-t p-4"><div className="flex items-end gap-2"><textarea className="input min-h-20" maxLength={2000} placeholder="Reply to the bank…" value={message} onChange={e=>setMessage(e.target.value)}/><button className="btn-primary px-3" disabled={sending||!message.trim()} onClick={reply} aria-label="Send reply"><Send size={18}/></button></div>{error&&<p className="mt-2 text-sm text-red-600">{error}</p>}</div></section></div>}</>;
}
