"use client";
import {useEffect,useMemo,useState} from "react";
import {HeartPulse,RefreshCw} from "lucide-react";
import {api} from "@/lib/api";
type Session={conversation_id:number;title:string;intent:string;sentiment:string;emotion:string;score:number;resolution_status:string;updated_at:string};
type History={customer_id:number;customer_name:string;sessions:Session[]};
const color=(value:string)=>value==="Highly Negative"?"bg-red-100 text-red-700":value==="Negative"?"bg-amber-100 text-amber-700":value==="Positive"?"bg-emerald-100 text-emerald-700":"bg-slate-100 text-slate-700";
export function CustomerSentimentHistory({customerId}:{customerId:number}){
 const [limit,setLimit]=useState(10),[history,setHistory]=useState<History|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true;setLoading(true);setError("");const load=()=>api<History>(`/customers/${customerId}/sentiment-history?limit=${limit}`).then(value=>{if(active){setHistory(value);setError("")}}).catch((error:any)=>{if(active)setError(error.message)}).finally(()=>{if(active)setLoading(false)});void load();const timer=window.setInterval(()=>{if(document.visibilityState==="visible")void load()},10000);return()=>{active=false;window.clearInterval(timer)}},[customerId,limit]);
 const summary=useMemo(()=>{const items=history?.sessions||[];const negative=items.filter(item=>item.sentiment.includes("Negative")).length,positive=items.filter(item=>item.sentiment==="Positive").length,average=items.length?items.reduce((sum,item)=>sum+item.score,0)/items.length:0;return {negative,positive,neutral:items.length-negative-positive,average}},[history]);
 return <section className="card p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><HeartPulse className="text-brand" size={20}/><h2 className="text-lg font-bold text-navy">Previous conversation sentiment</h2></div><label className="text-xs font-medium text-slate-500">Analyze previous <select className="ml-2 rounded-lg border bg-white px-3 py-2 text-sm text-slate-700" value={limit} onChange={event=>setLimit(Number(event.target.value))}>{[5,10,20,50].map(value=><option key={value} value={value}>{value} conversations</option>)}</select></label></div>{loading?<p className="mt-6 flex items-center gap-2 text-sm text-slate-500"><RefreshCw className="animate-spin" size={16}/>Loading sentiment history…</p>:error?<p className="mt-5 text-sm text-red-600">{error}</p>:history?.sessions.length?<><div className="mt-5 grid gap-3 sm:grid-cols-4"><Stat label="Average score" value={summary.average.toFixed(2)}/><Stat label="Positive" value={String(summary.positive)}/><Stat label="Neutral" value={String(summary.neutral)}/><Stat label="Negative" value={String(summary.negative)}/></div><div className="mt-5 space-y-2"><p className="text-xs text-slate-400">Oldest to newest</p>{history.sessions.map(session=><div key={session.conversation_id} className="flex flex-wrap items-center gap-3 rounded-xl border p-3 text-xs"><span className="w-10 font-semibold text-navy">#{session.conversation_id}</span><span className="min-w-0 flex-1 truncate font-medium">{session.title}</span><span className="text-slate-500">{session.intent}</span><span className={`badge ${color(session.sentiment)}`}>{session.sentiment}</span><span className="w-12 text-right font-semibold">{session.score.toFixed(1)}</span></div>)}</div></>:<p className="mt-6 text-sm text-slate-500">No previous conversation sentiment is available for this customer.</p>}</section>
}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 text-xl font-bold text-navy">{value}</p></div>}
