"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {ArrowDownUp,CalendarDays,CheckCircle2,ChevronRight,Clock3,Grid2X2,Headphones,Search,Send,TicketCheck,X} from "lucide-react";
import {api} from "@/lib/api";
type RequestRow={id:number;request_code:string;category:string;issue:string;customer_description?:string;priority:string;status:string;assigned_queue?:string;created_at:string;updated_at?:string};
type RequestMessage={id:number;message:string;sender_name:string;sender_type:"customer"|"employee";created_at:string};
const formatDate=(value:string)=>new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value));
const normalizedStatus=(status:string)=>status==="Closed"?"Resolved":status;
const activeStatuses=["Open","In Progress","Awaiting Customer","Escalated"];

export function CustomerServiceRequests(){
 const [rows,setRows]=useState<RequestRow[]>([]),[selected,setSelected]=useState<RequestRow|null>(null),[messages,setMessages]=useState<RequestMessage[]>([]),[message,setMessage]=useState(""),[sending,setSending]=useState(false),[closing,setClosing]=useState(false),[error,setError]=useState(""),[filter,setFilter]=useState("All"),[query,setQuery]=useState(""),[newest,setNewest]=useState(true),[loading,setLoading]=useState(true);
 useEffect(()=>{api<RequestRow[]>("/service-requests").then(setRows).catch((e:any)=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const counts=useMemo(()=>({All:rows.length,Open:rows.filter(r=>normalizedStatus(r.status)==="Open").length,"In Progress":rows.filter(r=>["In Progress","Awaiting Customer"].includes(r.status)).length,Resolved:rows.filter(r=>normalizedStatus(r.status)==="Resolved").length}),[rows]);
 const visible=useMemo(()=>rows.filter(row=>(filter==="All"||(filter==="In Progress"?["In Progress","Awaiting Customer"].includes(row.status):normalizedStatus(row.status)===filter))&&`${row.request_code} ${row.category} ${row.issue}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(new Date(b.created_at).getTime()-new Date(a.created_at).getTime())*(newest?1:-1)),[rows,filter,query,newest]);
 async function open(row:RequestRow){setSelected(row);setMessage("");setError("");try{setMessages(await api<RequestMessage[]>(`/service-requests/${row.id}/messages`))}catch(e:any){setError(e.message)}}
 async function reply(){if(!selected||!message.trim())return;setSending(true);setError("");try{const added=await api<RequestMessage>(`/service-requests/${selected.id}/messages`,{method:"POST",body:JSON.stringify({message})});setMessages(items=>[...items,added]);setMessage("")}catch(e:any){setError(e.message)}finally{setSending(false)}}
 async function closeRequest(){if(!selected||!activeStatuses.includes(selected.status)||!window.confirm(`Close service request ${selected.request_code}? You will no longer be able to send messages on this request.`))return;setClosing(true);setError("");try{const updated=await api<RequestRow>(`/service-requests/${selected.id}`,{method:"PATCH",body:JSON.stringify({status:"Closed"})});setRows(items=>items.map(item=>item.id===updated.id?{...item,...updated}:item));setSelected(current=>current?{...current,...updated}:current)}catch(e:any){setError(e.message)}finally{setClosing(false)}}
 return <div className="requests-page">
  <header className="requests-head"><div><p>Service requests</p><h1>Your service requests</h1><span>Track progress and communicate securely with the bank.</span></div><TicketCheck/></header>
  <section className="request-controls"><div className="request-tabs">{(["All","Open","In Progress","Resolved"] as const).map(value=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{value==="All"?<Grid2X2/>:value==="Resolved"?<CheckCircle2/>:<i/>}<span>{value} ({counts[value]})</span></button>)}</div><div className="request-search"><label><Search/><input aria-label="Search service requests" placeholder="Search request number or service type" value={query} onChange={e=>setQuery(e.target.value)}/></label><button onClick={()=>setNewest(value=>!value)}><ArrowDownUp/>{newest?"Newest first":"Oldest first"}</button></div></section>
  <section className="request-list">{loading?<div className="request-empty">Loading service requests…</div>:visible.length?visible.map(row=><button key={row.id} onClick={()=>open(row)} className={`request-card status-${normalizedStatus(row.status).toLowerCase().replace(" ","-")}`}><span className="request-icon"><TicketCheck/></span><span className="request-copy"><span className="request-code">{row.request_code}<i>{row.status}</i>{row.priority==="High"&&<i className="priority">High priority</i>}</span><b>{row.category}</b><small>{row.issue}</small></span><time><CalendarDays/>{formatDate(row.created_at)}</time><ChevronRight/></button>):<div className="request-empty"><TicketCheck/><h2>No matching requests</h2><p>Try another filter or ask the AI Assistant for help.</p></div>}{error&&!selected&&<p className="request-error">{error}</p>}</section>
  <section className="request-help"><span><Headphones/></span><div><b>Need help?</b><p>Ask the AI Assistant about a service request or another banking need.</p></div><Link href="/customer/chat?prompt=Please help me with my service request">Ask AI Assistant <ChevronRight/></Link></section>
  {selected&&<div className="request-drawer" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><section>
   <header><div><p>{selected.request_code}</p><h2>{selected.category}</h2><span><b>{selected.status}</b> · {selected.priority} priority</span></div><button onClick={()=>setSelected(null)} aria-label="Close drawer"><X/></button></header>
   <div className="request-detail-meta"><span><Clock3/>Created {formatDate(selected.created_at)}</span>{selected.assigned_queue&&<span>Handling team: {selected.assigned_queue}</span>}</div>
   {activeStatuses.includes(selected.status)&&<div className="border-b border-slate-200 bg-white px-6 py-3"><button className="btn-secondary w-full border-red-200 text-red-700 hover:bg-red-50" disabled={closing} onClick={closeRequest}><CheckCircle2 size={16}/>{closing?"Closing request…":"Close this service request"}</button></div>}
   <div className="request-thread"><div className="request-original"><small>Original request</small><p>{selected.issue}</p>{selected.customer_description&&<><small className="mt-3 block">Details you provided</small><p>{selected.customer_description}</p></>}</div>{messages.map(item=><div key={item.id} className={item.sender_type==="customer"?"request-customer-message":"request-bank-message"}><p>{item.message}</p><small>{item.sender_name} · {formatDate(item.created_at)}</small></div>)}{!messages.length&&<p className="request-no-messages">No follow-up messages yet.</p>}</div>
   {activeStatuses.includes(selected.status)?<footer><textarea maxLength={2000} placeholder="Reply securely to the bank…" value={message} onChange={e=>setMessage(e.target.value)}/><button disabled={sending||!message.trim()} onClick={reply} aria-label="Send reply"><Send/></button>{error&&<p>{error}</p>}</footer>:<div className="border-t border-emerald-200 bg-emerald-50 p-4 text-center text-xs font-semibold text-emerald-800">This request is closed. Its conversation remains available for your records.{error&&<span className="mt-1 block text-red-600">{error}</span>}</div>}
  </section></div>}
 </div>
}
