"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowDownUp,ChevronLeft,ChevronRight,IndianRupee,MapPin,RotateCcw,Search,ShieldCheck,UserRound,Users} from "lucide-react";
import {api} from "@/lib/api";
type Customer={id:number;customer_code:string;name:string;phone_number:string;segment:string;city:string;average_balance:number;rm_name:string};
const empty={query:"",segment:"",city:"",rmName:"",minBalance:"",maxBalance:""};
const money=(value:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(value||0);
export function CustomerDirectory(){
 const [rows,setRows]=useState<Customer[]>([]),[filters,setFilters]=useState(empty),[sort,setSort]=useState<"name"|"balance">("name"),[page,setPage]=useState(1),[loading,setLoading]=useState(true);const pageSize=10;
 useEffect(()=>{api<Customer[]>("/customers").then(setRows).finally(()=>setLoading(false))},[]);
 const options=useMemo(()=>({segments:[...new Set(rows.map(r=>r.segment).filter(Boolean))].sort(),cities:[...new Set(rows.map(r=>r.city).filter(Boolean))].sort(),rmNames:[...new Set(rows.map(r=>r.rm_name).filter(Boolean))].sort()}),[rows]);
 const visible=useMemo(()=>{const q=filters.query.trim().toLowerCase(),min=filters.minBalance===""?null:Number(filters.minBalance),max=filters.maxBalance===""?null:Number(filters.maxBalance);return rows.filter(r=>(!q||`${r.customer_code} ${r.name} ${r.phone_number}`.toLowerCase().includes(q))&&(!filters.segment||r.segment===filters.segment)&&(!filters.city||r.city===filters.city)&&(!filters.rmName||r.rm_name===filters.rmName)&&(min===null||r.average_balance>=min)&&(max===null||r.average_balance<=max)).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):b.average_balance-a.average_balance)},[rows,filters,sort]);
 const pageCount=Math.max(1,Math.ceil(visible.length/pageSize)),pageRows=visible.slice((page-1)*pageSize,page*pageSize),update=(key:keyof typeof empty,value:string)=>{setFilters(current=>({...current,[key]:value}));setPage(1)};
 const totalBalance=rows.reduce((sum,row)=>sum+Number(row.average_balance||0),0),privilege=rows.filter(row=>row.segment==="Privilege").length;
 return <div className="customer-directory">
  <header className="directory-head"><div className="directory-title-icon"><Users/></div><div><p>Customer intelligence</p><h1>Customer 360</h1><span>Find customers and open a complete relationship and sentiment view.</span></div></header>
  <section className="directory-stats"><article><Users/><span><small>Total customers</small><b>{rows.length}</b></span></article><article><ShieldCheck/><span><small>Privilege customers</small><b>{privilege}</b></span></article><article><IndianRupee/><span><small>Total relationship value</small><b>{money(totalBalance)}</b></span></article><article><MapPin/><span><small>Cities represented</small><b>{options.cities.length}</b></span></article></section>
  <section className="directory-filters"><div className="directory-search"><Search/><input placeholder="Search by name, customer code, or phone" aria-label="Search customers" value={filters.query} onChange={e=>update("query",e.target.value)}/></div><Filter label="Segment" value={filters.segment} options={options.segments} onChange={v=>update("segment",v)}/><Filter label="City" value={filters.city} options={options.cities} onChange={v=>update("city",v)}/><Filter label="Relationship manager" value={filters.rmName} options={options.rmNames} onChange={v=>update("rmName",v)}/><div className="balance-filter"><label>Balance range</label><span><IndianRupee/><input type="number" min="0" placeholder="Minimum" value={filters.minBalance} onChange={e=>update("minBalance",e.target.value)}/><i>to</i><input type="number" min="0" placeholder="Maximum" value={filters.maxBalance} onChange={e=>update("maxBalance",e.target.value)}/></span></div><footer><span>Showing <b>{visible.length}</b> of {rows.length} customers</span><div><button onClick={()=>setSort(value=>value==="name"?"balance":"name")}><ArrowDownUp/>Sort: {sort==="name"?"Name":"Balance"}</button><button disabled={!Object.values(filters).some(Boolean)} onClick={()=>{setFilters(empty);setPage(1)}}><RotateCcw/>Clear filters</button></div></footer></section>
  <section className="directory-table"><div className="directory-table-head"><span>Customer</span><span>Segment &amp; location</span><span>Average balance</span><span>Relationship manager</span><span>Action</span></div>{loading?<div className="directory-empty">Loading customers…</div>:pageRows.length?pageRows.map(customer=><article key={customer.id}><div className="directory-customer"><i>{customer.name.charAt(0)}</i><span><b>{customer.name}</b><small>{customer.customer_code} · {customer.phone_number||"No phone"}</small></span></div><div className="directory-location"><span className={`segment ${customer.segment?.toLowerCase()}`}>{customer.segment}</span><small><MapPin/>{customer.city}</small></div><strong>{money(customer.average_balance)}</strong><div className="directory-rm"><UserRound/><span>{customer.rm_name||"Unassigned"}</span></div><Link href={`/bank/customers/${customer.id}`}>Open 360 <ChevronRight/></Link></article>):<div className="directory-empty"><Search/><h2>No customers found</h2><p>Try changing or clearing the selected filters.</p></div>}<footer><span>Page {page} of {pageCount}</span><div><button disabled={page===1} onClick={()=>setPage(value=>value-1)}><ChevronLeft/></button><button disabled={page===pageCount} onClick={()=>setPage(value=>value+1)}><ChevronRight/></button></div></footer></section>
 </div>
}
function Filter({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}){return <label className="directory-select"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}><option value="">All</option>{options.map(option=><option key={option}>{option}</option>)}</select></label>}
