"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {CoachingPlan} from "@/components/coaching-plan";
import {ArrowRight,Check,Edit3,Target,Trash2,X} from "lucide-react";
import {api} from "@/lib/api";

const fields=[["target_amount","Target amount"],["saved_amount","Amount already saved"],["monthly_income","Monthly income"],["monthly_expenses","Monthly expenses"],["timeline_months","Timeline (months)"]] as const;

export function FinancialGoals(){
 const [goals,setGoals]=useState<any[]>([]),[error,setError]=useState("");
 useEffect(()=>{api<any[]>("/financial-goals").then(setGoals).catch((e:any)=>setError(e.message))},[]);
 return <>
  <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold text-navy">Financial goals</h1><p className="mt-2 text-slate-500">Personalized guidance and progress tracking—not product selling.</p></div><div className="flex flex-wrap gap-2"><Link href="/customer/chat?mode=coach&prompt=Create%20a%20savings%20plan%20to%20buy%20a%20home" className="btn-secondary"><Target size={17}/>Home goal</Link><Link href="/customer/chat?mode=coach" className="btn-primary">Start coaching conversation <ArrowRight size={17}/></Link></div></div>
  <div className="mt-7 grid gap-5 lg:grid-cols-2">{goals.map(goal=><GoalCard key={goal.id} goal={goal} onUpdated={updated=>setGoals(items=>items.map(item=>item.id===updated.id?updated:item))} onRemoved={id=>setGoals(items=>items.filter(item=>item.id!==id))}/>)}{!goals.length&&<div className="card p-12 text-center text-slate-500 lg:col-span-2">{error||"No goals yet. Start a coaching conversation to build your first plan."}</div>}</div>
 </>
}

function GoalCard({goal,onUpdated,onRemoved}:{goal:any;onUpdated:(goal:any)=>void;onRemoved:(id:number)=>void}){
 const [editing,setEditing]=useState(false),[draft,setDraft]=useState<any>(goal),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const plan=goal.coaching_plan||{},progress=goal.target_amount?Math.min(100,goal.saved_amount/goal.target_amount*100):0;
 function cancel(){setDraft(goal);setError("");setEditing(false)}
 async function save(){setBusy(true);setError("");try{const updated=await api<any>(`/financial-goals/${goal.id}`,{method:"PUT",body:JSON.stringify({name:draft.name,target_amount:Number(draft.target_amount),saved_amount:Number(draft.saved_amount),monthly_income:Number(draft.monthly_income),monthly_expenses:Number(draft.monthly_expenses),timeline_months:Number(draft.timeline_months)})});onUpdated(updated);setDraft(updated);setEditing(false)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function remove(){if(!window.confirm(`Remove “${goal.name}”? This cannot be undone.`))return;setBusy(true);setError("");try{await api(`/financial-goals/${goal.id}`,{method:"DELETE"});onRemoved(goal.id)}catch(e:any){setError(e.message);setBusy(false)}}
 if(editing)return <section className="card p-6"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-xl font-bold text-navy"><Edit3 className="text-brand"/>Edit financial goal</h2><button onClick={cancel} className="rounded-lg p-2 hover:bg-slate-100" aria-label="Cancel editing"><X size={19}/></button></div><label className="mt-5 block text-xs font-medium text-slate-500">Goal name<input className="input mt-1" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><div className="mt-4 grid gap-3 sm:grid-cols-2">{fields.map(([field,label])=><label key={field} className="text-xs font-medium text-slate-500">{label}<input className="input mt-1" type="number" min="0" step={field==="timeline_months"?"1":"1000"} value={draft[field]??0} onChange={e=>setDraft({...draft,[field]:e.target.value})}/></label>)}</div>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-5 flex gap-2"><button className="btn-primary" onClick={save} disabled={busy||!draft.name.trim()}><Check size={17}/>{busy?"Saving…":"Save changes"}</button><button className="btn-secondary" onClick={cancel} disabled={busy}>Cancel</button></div><p className="mt-3 text-xs text-slate-400">The plan will be recalculated automatically.</p></section>;
 return <section className="card p-6"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-2"><Target className="text-brand"/><h2 className="text-xl font-bold text-navy">{goal.name}</h2></div><div className="flex flex-wrap items-center justify-end gap-2"><span className="badge bg-emerald-50 text-emerald-700">{goal.status}</span><button onClick={()=>setEditing(true)} className="btn-secondary px-3 py-2 text-xs"><Edit3 size={15}/>Edit</button><button onClick={remove} disabled={busy} className="btn-secondary px-3 py-2 text-xs text-red-600"><Trash2 size={15}/>{busy?"Removing…":"Remove"}</button></div></div>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-5 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-brand" style={{width:`${progress}%`}}/></div><p className="mt-2 text-sm text-slate-500">₹{Number(goal.saved_amount).toLocaleString("en-IN")} saved of ₹{Number(goal.target_amount).toLocaleString("en-IN")}</p><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><Metric label="Monthly income" value={goal.monthly_income}/><Metric label="Monthly expenses" value={goal.monthly_expenses}/><Metric label="Monthly surplus" value={plan.monthly_surplus}/><Metric label="Monthly goal" value={goal.monthly_required}/><Metric label="Timeline" value={`${goal.timeline_months||0} months`} money={false}/><Metric label="Emergency buffer" value={plan.emergency_fund_target}/></div><CoachingPlan plan={plan} conversationId={goal.conversation_id}/>{!plan.stage&&plan.feasible!==undefined&&<p className={`mt-5 rounded-xl p-3 text-sm font-semibold ${plan.feasible?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-800"}`}>{plan.feasible?"This goal fits within the current monthly surplus.":plan.suggested_timeline_months?`Consider a timeline of about ${plan.suggested_timeline_months} months or reduce discretionary expenses.`:"Reduce expenses or increase income before committing to this goal."}</p>}{plan.guidance?.length>0&&<ul className="mt-5 list-disc space-y-2 pl-5 text-sm text-slate-600">{plan.guidance.map((item:string)=><li key={item}>{item}</li>)}</ul>}</section>
}
function Metric({label,value,money=true}:{label:string;value:any;money?:boolean}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 font-bold">{money?`₹${Number(value||0).toLocaleString("en-IN",{maximumFractionDigits:0})}`:value}</p></div>}
