"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowDownUp,CheckCircle2,ChevronRight,Flame,Search,Target,TrendingUp,UserRoundCheck,UsersRound,X} from "lucide-react";
import {api} from "@/lib/api";
type Lead={id:number;customer_id:number;customer_name:string;customer_code:string;conversation_id?:number;product:string;score:number;temperature:string;journey_stage:string;qualification_data?:Record<string,unknown>;drop_off_detected?:boolean;status:string;next_action:string;reasons?:string[];created_at:string};
const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export function LeadIntelligence(){
 const [rows,setRows]=useState<Lead[]>([]),[filter,setFilter]=useState("All"),[query,setQuery]=useState(""),[sortHigh,setSortHigh]=useState(true),[selected,setSelected]=useState<Lead|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{api<Lead[]>("/leads").then(setRows).finally(()=>setLoading(false))},[]);
 const hot=rows.filter(r=>r.temperature==="Hot").length,warm=rows.filter(r=>r.temperature==="Warm").length,qualified=rows.filter(r=>r.status==="Qualified").length,conversion=rows.length?Math.round(qualified/rows.length*100):0;
 const visible=useMemo(()=>rows.filter(row=>(filter==="All"||(filter==="Qualified"?row.status==="Qualified":row.temperature===filter))&&`${row.customer_name} ${row.customer_code} ${row.product} ${row.next_action}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(b.score-a.score)*(sortHigh?1:-1)),[rows,filter,query,sortHigh]);
 return <div className="lead-page"><header className="lead-head"><div><p>Pipeline intelligence</p><h1>Lead intelligence</h1><span>Prioritize qualified interest and guide every customer toward the right next step.</span></div><Target/></header>
  <section className="lead-kpis"><Kpi icon={<Target/>} label="Total leads" value={rows.length} tone="blue"/><Kpi icon={<Flame/>} label="Hot leads" value={hot} tone="red"/><Kpi icon={<UsersRound/>} label="Warm leads" value={warm} tone="amber"/><Kpi icon={<UserRoundCheck/>} label="Qualified" value={qualified} tone="green"/><Kpi icon={<TrendingUp/>} label="Conversion rate" value={`${conversion}%`} tone="purple"/></section>
  <section className="lead-tools"><div>{["All","Hot","Warm","Qualified"].map(value=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{value}{value!=="All"&&<span>{value==="Hot"?hot:value==="Warm"?warm:qualified}</span>}</button>)}</div><label><Search/><input placeholder="Customer, product, or next action" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="lead-sort" onClick={()=>setSortHigh(value=>!value)}><ArrowDownUp/>{sortHigh?"Highest score":"Lowest score"}</button></section>
  <section className="lead-list">{loading?<div className="lead-empty">Loading lead pipeline…</div>:visible.length?visible.map(row=><article key={row.id} className={`lead-card ${row.temperature.toLowerCase()}`}><div className="lead-customer"><i>{row.customer_name?.charAt(0)||"C"}</i><span><b>{row.customer_name||row.customer_code}</b><small>{row.customer_code} · Lead #{row.id}</small></span></div><div className="lead-product"><small>Product</small><b>{row.product}</b><span>{row.journey_stage} stage</span></div><div className="lead-score"><span><b>{row.score}</b>/100</span><i><em style={{width:`${row.score}%`}}/></i></div><span className={`lead-temperature ${row.temperature.toLowerCase()}`}>{row.temperature}</span><div className="lead-next"><small>Next best action</small><b>{row.next_action}</b>{row.drop_off_detected&&<span>Drop-off detected</span>}</div><button onClick={()=>setSelected(row)} aria-label={`View lead ${row.id}`}><ChevronRight/></button></article>):<div className="lead-empty"><Search/><h2>No matching leads</h2><p>Try another search or pipeline filter.</p></div>}</section>
  <div className="lead-tip"><TrendingUp/><p><b>Pipeline focus</b><span>Review high-scoring and dropped-off leads first, then complete the documented next action.</span></p></div>
  {selected&&<div className="lead-drawer" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><section><header><div><p>{selected.customer_code}</p><h2>{selected.customer_name}</h2><span>{selected.product} · {selected.temperature} lead</span></div><button onClick={()=>setSelected(null)}><X/></button></header><div className="lead-detail"><div className="lead-detail-score"><Target/><span><small>Lead score</small><b>{selected.score}/100</b></span><i className={selected.temperature.toLowerCase()}>{selected.temperature}</i></div><h3>Qualification progress</h3><div className="lead-progress"><i style={{width:`${selected.score}%`}}/></div><p className="lead-stage">Current stage: <b>{selected.journey_stage}</b> · Status: <b>{selected.status}</b></p><h3>Captured information</h3><dl>{Object.entries(selected.qualification_data||{}).length?Object.entries(selected.qualification_data||{}).map(([key,value])=><div key={key}><dt>{label(key)}</dt><dd>{String(value)}</dd></div>):<p>No qualification details captured yet.</p>}</dl>{selected.reasons?.length?<><h3>Why this lead was identified</h3><ul>{selected.reasons.map(reason=><li key={reason}><CheckCircle2/>{reason}</li>)}</ul></>:null}<div className="lead-action"><small>Recommended next action</small><b>{selected.next_action}</b></div></div><footer><Link href={`/bank/customers/${selected.customer_id}`}>Open Customer 360</Link>{selected.conversation_id&&<Link href={`/bank/conversations/${selected.conversation_id}`}>Review conversation</Link>}</footer></section></div>}
 </div>
}
function Kpi({icon,label,value,tone}:{icon:React.ReactNode;label:string;value:number|string;tone:string}){return <article className={tone}><span>{icon}</span><div><small>{label}</small><b>{value}</b></div></article>}
