"use client";
import {useEffect,useMemo,useState} from "react";
import {CalendarDays,CheckCircle2,Mail,Phone,RefreshCw,Search,ShieldAlert,UserRound,X} from "lucide-react";
import {api} from "@/lib/api";

const statuses=["Monitoring","Intervention Planned","Content Approved","Closed"];
export function RetentionManager(){
 const [items,setItems]=useState<any[]>([]),[q,setQ]=useState(""),[fromDate,setFromDate]=useState(""),[toDate,setToDate]=useState(""),[saving,setSaving]=useState<number>(),[error,setError]=useState(""),[notice,setNotice]=useState(""),[emailDraft,setEmailDraft]=useState<any>(null);
 const load=()=>api<any[]>("/retention").then(rows=>{setItems(rows);setError("")}).catch((e:any)=>setError(e.message));
 useEffect(()=>{load();const timer=window.setInterval(load,15000);const visible=()=>{if(document.visibilityState==="visible")load()};document.addEventListener("visibilitychange",visible);return()=>{window.clearInterval(timer);document.removeEventListener("visibilitychange",visible)}},[]);
 const visible=useMemo(()=>items.filter(item=>{const value=new Date(item.activity_at||item.created_at).getTime();return JSON.stringify(item).toLowerCase().includes(q.toLowerCase())&&(!fromDate||value>=new Date(`${fromDate}T00:00:00`).getTime())&&(!toDate||value<=new Date(`${toDate}T23:59:59.999`).getTime())}).sort((a,b)=>new Date(b.activity_at||b.created_at).getTime()-new Date(a.activity_at||a.created_at).getTime()),[items,q,fromDate,toDate]);
 async function refresh(){setNotice("");await api("/retention/refresh",{method:"POST"});await load()}
 async function regenerate(item:any){setSaving(item.id);setError("");setNotice("");try{const updated=await api<any>(`/retention/${item.id}/regenerate`,{method:"POST"});setItems(rows=>rows.map(row=>row.id===item.id?{...row,...updated}:row));setNotice(updated.knowledge_sources?.length?`Generated ${item.customer_name}'s message using the approved engagement guide.`:`No approved guide passage or AI response was available; the safe fallback was retained.`)}catch(e:any){setError(e.message)}finally{setSaving(undefined)}}
 async function review(item:any,status:string){setSaving(item.id);setError("");setNotice("");try{const updated=await api<any>(`/retention/${item.id}`,{method:"PATCH",body:JSON.stringify({status,communication_draft:item.communication_draft})});setItems(rows=>rows.map(row=>row.id===item.id?{...row,...updated}:row));setNotice(status==="Intervention Planned"?`RM intervention planned for ${item.customer_name}. Assigned RM: ${item.rm_name||"Not assigned"}.`:`${item.customer_name} updated to ${status}.`)}catch(e:any){setError(e.message)}finally{setSaving(undefined)}}
 function openEmail(item:any){setError("");setEmailDraft({item,recipient:item.email_address||"",subject:`A message from Union Bank of India`,message:item.communication_draft||""})}
 async function sendEmail(){if(!emailDraft)return;const {item,recipient,subject,message}=emailDraft;setSaving(item.id);setError("");try{if(item.status!=="Content Approved")await api<any>(`/retention/${item.id}`,{method:"PATCH",body:JSON.stringify({status:"Content Approved",communication_draft:message.trim()})});const result=await api<any>(`/retention/${item.id}/send-email`,{method:"POST",body:JSON.stringify({recipient:recipient.trim(),subject:subject.trim(),message:message.trim()})});setItems(rows=>rows.map(row=>row.id===item.id?{...row,status:"Content Approved",communication_draft:message.trim()}:row));setEmailDraft(null);setNotice(`Reviewed content approved and email submitted to the provider for ${result.recipient}.`)}catch(e:any){setError(e.message)}finally{setSaving(undefined)}}
 return <>
  <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold text-navy">Customer retention & win-back</h1><p className="mt-1 text-slate-500">Identify attrition risk, understand its cause, and plan human-reviewed recovery.</p></div><div className="flex flex-wrap gap-2"><label className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input className="input pl-9" placeholder="Search risk cases" value={q} onChange={e=>setQ(e.target.value)}/></label><label className="relative"><CalendarDays className="absolute left-3 top-3 text-slate-400" size={17}/><input aria-label="Retention from date" type="date" className="input pl-9" value={fromDate} onChange={e=>setFromDate(e.target.value)}/></label><label className="relative"><CalendarDays className="absolute left-3 top-3 text-slate-400" size={17}/><input aria-label="Retention to date" type="date" className="input pl-9" min={fromDate} value={toDate} onChange={e=>setToDate(e.target.value)}/></label><button className="btn-secondary" onClick={refresh}><RefreshCw size={16}/>Refresh</button></div></div>
  <div className="mt-6 grid gap-4 sm:grid-cols-3"><Stat label="Critical risk" value={items.filter(item=>item.level==="Critical").length} tone="red"/><Stat label="High risk" value={items.filter(item=>item.level==="High").length} tone="amber"/><Stat label="Win-back cases" value={items.filter(item=>item.case_type==="Win-back").length} tone="blue"/></div>
  {error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p className="mt-4 flex items-center gap-2 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700"><CheckCircle2 size={17}/>{notice}</p>}
  <div className="mt-6 grid gap-5 xl:grid-cols-2">{visible.map(item=><section className="card p-6" key={item.id}>
   <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-brand">{item.case_type} • {item.customer_name}</p><h2 className="mt-1 flex items-center gap-2 text-xl font-bold text-navy"><ShieldAlert size={19}/>{item.level} attrition risk</h2><p className="mt-1 text-xs text-slate-500">Customer ID: {item.customer_code||item.customer_id} · Latest interaction {new Date(item.activity_at||item.created_at).toLocaleString()}</p></div><div className="text-right"><span className="text-3xl font-bold text-navy">{item.score}</span><span className="text-xs text-slate-400">/100</span></div></div>
   <div className="mt-4 grid gap-2 rounded-xl bg-slate-50 p-4 text-sm sm:grid-cols-2"><span className="flex items-center gap-2"><Phone size={15}/>{item.phone_number||"Phone unavailable"}</span><span className="flex items-center gap-2"><Mail size={15}/>{item.email_address||"Email unavailable"}</span><span className="flex items-center gap-2 sm:col-span-2"><UserRound size={15}/>Assigned RM: {item.rm_name||"Not assigned"}</span></div>
   <div className="mt-5 rounded-xl border border-slate-200 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Latest conversation summary</p><p className="mt-1 font-semibold text-navy">{item.conversation_title||"Recent customer conversation"}</p><p className="mt-2 text-sm leading-6 text-slate-600">{item.conversation_summary||"No conversation summary is available."}</p><div className="mt-3 flex flex-wrap gap-2 text-xs"><span className="badge bg-slate-100 text-slate-700">Sentiment: {item.conversation_sentiment||"Unknown"}</span><span className="badge bg-slate-100 text-slate-700">Resolution: {item.conversation_resolution||"Unknown"}</span></div></div>
   <div className="mt-5"><p className="text-xs font-semibold uppercase text-slate-400">Why this customer is at risk</p><p className="mt-2 text-sm leading-6 text-slate-700">{item.risk_summary}</p><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-slate-600">{item.reasons.map((reason:string)=><li key={reason}>{reason}</li>)}</ul></div>
   <div className="mt-5 rounded-xl bg-amber-50 p-4"><p className="text-xs font-semibold uppercase text-amber-700">Recommended action</p><p className="mt-1 text-sm leading-6 text-amber-900">{item.suggested_action}</p></div>
   {item.status==="Intervention Planned"&&<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="flex items-center gap-2 font-semibold text-emerald-900"><CheckCircle2 size={17}/>RM intervention planned</p><p className="mt-1 text-sm text-emerald-800">{item.rm_name||"The assigned relationship manager"} can contact the customer using the verified details above.</p>{item.phone_number&&<div className="mt-3"><a className="btn-secondary" href={`tel:${item.phone_number}`}><Phone size={15}/>Call customer</a></div>}</div>}
   <label className="mt-5 block text-sm font-semibold">Case status<select className="input mt-2" value={item.status} disabled={saving===item.id} onChange={e=>review(item,e.target.value)}>{statuses.map(status=><option key={status}>{status}</option>)}</select></label>
   <label className="mt-5 block text-sm font-semibold">Personalized {item.case_type.toLowerCase()} message<textarea className="input mt-2 min-h-32 leading-6" maxLength={2000} value={item.communication_draft||""} onChange={e=>setItems(rows=>rows.map(row=>row.id===item.id?{...row,communication_draft:e.target.value}:row))}/></label>
   {item.knowledge_sources?.length?<div className="mt-3 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs text-blue-800"><p className="font-semibold">Generated with approved engagement guidance</p><p className="mt-1">{item.knowledge_sources.map((source:any)=>`${source.title} · page ${source.page}`).join("; ")}</p></div>:<p className="mt-2 text-xs text-slate-400">{item.message_generated_by||"Deterministic fallback"} · No engagement-document passage was used for this draft.</p>}
   <p className="mt-2 text-xs text-slate-400">Employee review required. This PoC does not send the message automatically.</p>
   <div className="mt-4 flex flex-wrap gap-2"><button className="btn-secondary" disabled={saving===item.id} onClick={()=>regenerate(item)}><RefreshCw size={15}/>{saving===item.id?"Generating…":"Generate with approved guide"}</button><button className="btn-primary" disabled={saving===item.id||!item.communication_draft.trim()} onClick={()=>review(item,"Content Approved")}>Approve content</button><button className="btn-secondary" disabled={saving===item.id||!item.communication_draft.trim()||!item.email_address} onClick={()=>openEmail(item)}><Mail size={15}/>Review &amp; send email</button><button className="btn-secondary" disabled={saving===item.id||item.status==="Intervention Planned"} onClick={()=>review(item,"Intervention Planned")}>{item.status==="Intervention Planned"?"Intervention planned":"Plan RM intervention"}</button></div>
  </section>)}</div>
  {emailDraft&&<RetentionEmailEditor draft={emailDraft} setDraft={setEmailDraft} saving={saving===emailDraft.item.id} error={error} onSend={sendEmail}/>} 
 </>
}
function Stat({label,value,tone}:{label:string;value:number;tone:string}){const color=tone==="red"?"bg-red-50 text-red-700":tone==="amber"?"bg-amber-50 text-amber-700":"bg-blue-50 text-blue-700";return <div className={`rounded-2xl p-5 ${color}`}><p className="text-sm font-medium">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>}
function RetentionEmailEditor({draft,setDraft,saving,error,onSend}:{draft:any;setDraft:React.Dispatch<React.SetStateAction<any>>;saving:boolean;error:string;onSend:()=>void}){const update=(values:any)=>setDraft((current:any)=>current?{...current,...values}:current);const canSend=draft.recipient.trim()&&draft.subject.trim()&&draft.message.trim();return <div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-950/55 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-2xl rounded-2xl bg-white shadow-2xl"><header className="flex items-start justify-between border-b px-6 py-5"><div><h2 className="text-xl font-bold text-navy">Review and send retention email</h2><p className="mt-1 text-sm text-slate-500">Confirm the recipient, subject, and approved message.</p></div><button className="rounded-lg p-2" disabled={saving} onClick={()=>setDraft(null)}><X size={20}/></button></header><div className="space-y-4 px-6 py-5">{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<label className="block text-sm font-semibold">To<input type="email" className="input mt-2" value={draft.recipient} onChange={e=>update({recipient:e.target.value})}/></label><label className="block text-sm font-semibold">Subject<input className="input mt-2" value={draft.subject} onChange={e=>update({subject:e.target.value})}/></label><label className="block text-sm font-semibold">Message<textarea className="input mt-2 min-h-56 leading-6" maxLength={5000} value={draft.message} onChange={e=>update({message:e.target.value})}/></label></div><footer className="flex justify-end gap-3 border-t px-6 py-4"><button className="btn-secondary" disabled={saving} onClick={()=>setDraft(null)}>Cancel</button><button className="btn-primary" disabled={saving||!canSend} onClick={onSend}><Mail size={16}/>{saving?"Sending…":"Send email"}</button></footer></div></div>}
