"use client";
import {useEffect,useMemo,useState} from "react";
import {MessageSquarePlus,Search,X} from "lucide-react";
import {api} from "@/lib/api";

type RequestRow={id:number;request_code:string;customer_id:number;category:string;issue:string;priority:string;status:string;created_at:string};
type Comment={id:number;comment:string;author_name:string;created_at:string};
type RequestMessage={id:number;message:string;sender_name:string;sender_type:"customer"|"employee";created_at:string};
const statuses=["Open","In Progress","Awaiting Customer","Resolved","Closed"];

export function ServiceRequestManager(){
 const [rows,setRows]=useState<RequestRow[]>([]),[selected,setSelected]=useState<RequestRow|null>(null),[comments,setComments]=useState<Comment[]>([]),[comment,setComment]=useState(""),[messages,setMessages]=useState<RequestMessage[]>([]),[message,setMessage]=useState(""),[q,setQ]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=()=>api<RequestRow[]>("/service-requests").then(setRows).catch((e:any)=>setError(e.message));
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>rows.filter(row=>JSON.stringify(row).toLowerCase().includes(q.toLowerCase())),[rows,q]);
 async function open(row:RequestRow){setSelected(row);setError("");setComment("");setMessage("");try{const [notes,thread]=await Promise.all([api<Comment[]>(`/service-requests/${row.id}/comments`),api<RequestMessage[]>(`/service-requests/${row.id}/messages`)]);setComments(notes);setMessages(thread)}catch(e:any){setError(e.message)}}
 async function changeStatus(status:string){if(!selected)return;setSaving(true);setError("");try{const updated=await api<RequestRow>(`/service-requests/${selected.id}`,{method:"PATCH",body:JSON.stringify({status})});setSelected(updated);setRows(items=>items.map(item=>item.id===updated.id?updated:item))}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 async function addComment(){if(!selected||!comment.trim())return;setSaving(true);setError("");try{const added=await api<Comment>(`/service-requests/${selected.id}/comments`,{method:"POST",body:JSON.stringify({comment})});setComments(items=>[...items,added]);setComment("")}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 async function sendMessage(){if(!selected||!message.trim())return;setSaving(true);setError("");try{const added=await api<RequestMessage>(`/service-requests/${selected.id}/messages`,{method:"POST",body:JSON.stringify({message})});setMessages(items=>[...items,added]);setMessage("")}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 return <><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold text-navy">Service requests</h1><p className="mt-1 text-slate-500">Review requests, update progress, and record internal notes.</p></div><label className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input className="input pl-9" placeholder="Search requests" value={q} onChange={e=>setQ(e.target.value)}/></label></div>
 <div className="card mt-6 overflow-x-auto"><table><thead><tr>{["Request","Customer","Category","Issue","Priority","Status","Created","Action"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{visible.map(row=><tr key={row.id} className="hover:bg-slate-50"><td className="font-semibold text-navy">{row.request_code}</td><td>{row.customer_id}</td><td>{row.category}</td><td className="max-w-xs">{row.issue}</td><td><span className={`badge ${row.priority==="High"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}>{row.priority}</span></td><td><span className="badge bg-blue-50 text-blue-700">{row.status}</span></td><td>{new Date(row.created_at).toLocaleString()}</td><td><button className="btn-secondary whitespace-nowrap" onClick={()=>open(row)}><MessageSquarePlus size={16}/>Manage</button></td></tr>)}</tbody></table>{!visible.length&&<p className="p-12 text-center text-slate-500">No matching requests.</p>}</div>
 {selected&&<div className="fixed inset-0 z-50 flex justify-end bg-slate-950/30" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><section className="h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-brand">{selected.request_code}</p><h2 className="mt-1 text-2xl font-bold text-navy">Manage service request</h2></div><button className="rounded-lg p-2 hover:bg-slate-100" onClick={()=>setSelected(null)} aria-label="Close"><X/></button></div>
 <div className="mt-6 rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{selected.category} • Customer {selected.customer_id}</p><p className="mt-2 text-sm leading-6">{selected.issue}</p><p className="mt-2 text-xs font-semibold text-slate-500">Priority: {selected.priority}</p></div>
 <label className="mt-6 block text-sm font-semibold">Status<select className="input mt-2" value={selected.status} disabled={saving} onChange={e=>changeStatus(e.target.value)}>{statuses.map(status=><option key={status}>{status}</option>)}</select></label>
 <div className="mt-7"><h3 className="font-semibold">Customer conversation</h3><p className="mt-1 text-xs text-slate-500">Messages here are visible to the customer.</p><div className="mt-4 space-y-3">{messages.map(item=><div key={item.id} className={`max-w-[85%] rounded-xl p-3 ${item.sender_type==="employee"?"ml-auto bg-navy text-white":"bg-slate-100"}`}><p className="text-sm leading-6">{item.message}</p><p className={`mt-2 text-xs ${item.sender_type==="employee"?"text-slate-300":"text-slate-400"}`}>{item.sender_name} • {new Date(item.created_at).toLocaleString()}</p></div>)}{!messages.length&&<p className="rounded-xl border border-dashed p-5 text-center text-sm text-slate-400">No customer-visible messages yet.</p>}</div><textarea className="input mt-4 min-h-24" maxLength={2000} placeholder="Write a reply to the customer…" value={message} onChange={e=>setMessage(e.target.value)}/><button className="btn-primary mt-3" disabled={saving||!message.trim()} onClick={sendMessage}>Send to customer</button></div>
 <div className="mt-8 border-t pt-7"><h3 className="font-semibold">Internal comments</h3><p className="mt-1 text-xs text-slate-500">Visible to bank employees only.</p><div className="mt-4 space-y-3">{comments.map(item=><div key={item.id} className="rounded-xl border p-3"><p className="text-sm leading-6">{item.comment}</p><p className="mt-2 text-xs text-slate-400">{item.author_name} • {new Date(item.created_at).toLocaleString()}</p></div>)}{!comments.length&&<p className="rounded-xl border border-dashed p-5 text-center text-sm text-slate-400">No internal comments yet.</p>}</div>
 <textarea className="input mt-4 min-h-28" maxLength={2000} placeholder="Add investigation notes, customer follow-up details, or resolution comments…" value={comment} onChange={e=>setComment(e.target.value)}/><button className="btn-primary mt-3" disabled={saving||!comment.trim()} onClick={addComment}>Add internal comment</button></div>{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}</section></div>}</>;
}
