"use client";
import {useEffect,useMemo,useState} from "react";
import {ArrowDownUp,ArrowLeft,ArrowRight,CalendarDays,ChevronDown,Clock3,FileText,MessageSquarePlus,MoreVertical,RotateCcw,Search,ShieldAlert,X} from "lucide-react";
import {api} from "@/lib/api";

type RequestRow={id:number;request_code:string;customer_id:number;customer_code:string;customer_name:string;category:string;issue:string;priority:string;status:string;assigned_queue:string;escalation_level:string;routing_reason:string;created_at:string};
type Comment={id:number;comment:string;author_name:string;created_at:string};
type RequestMessage={id:number;message:string;sender_name:string;sender_type:"customer"|"employee";created_at:string};
const statuses=["Open","In Progress","Awaiting Customer","Resolved","Closed"];
const PAGE_SIZE=10;

export function ServiceRequestManager(){
 const [rows,setRows]=useState<RequestRow[]>([]),[selected,setSelected]=useState<RequestRow|null>(null),[comments,setComments]=useState<Comment[]>([]),[comment,setComment]=useState(""),[messages,setMessages]=useState<RequestMessage[]>([]),[message,setMessage]=useState(""),[q,setQ]=useState("");
 const [category,setCategory]=useState("All"),[status,setStatus]=useState("All"),[priority,setPriority]=useState("All"),[queue,setQueue]=useState("All"),[days,setDays]=useState("30"),[page,setPage]=useState(1),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=()=>api<RequestRow[]>("/service-requests").then(setRows).catch((e:any)=>setError(e.message));
 useEffect(()=>{load()},[]);
 const options=useMemo(()=>({categories:unique(rows.map(r=>r.category)),statuses:unique(rows.map(r=>r.status)),priorities:unique(rows.map(r=>r.priority)),queues:unique(rows.map(r=>r.assigned_queue||"Standard Queue"))}),[rows]);
 const filtered=useMemo(()=>{const term=q.trim().toLowerCase(),cutoff=Date.now()-Number(days)*86400000;return rows.filter(row=>(!term||`${row.request_code} ${row.customer_code} ${row.customer_name} ${row.category} ${row.issue}`.toLowerCase().includes(term))&&(category==="All"||row.category===category)&&(status==="All"||row.status===status)&&(priority==="All"||row.priority===priority)&&(queue==="All"||(row.assigned_queue||"Standard Queue")===queue)&&(days==="All"||new Date(row.created_at).getTime()>=cutoff))},[rows,q,category,status,priority,queue,days]);
 const pageCount=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));
 useEffect(()=>setPage(1),[q,category,status,priority,queue,days]);
 const visible=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
 const stats=useMemo(()=>({total:rows.length,open:rows.filter(r=>r.status==="Open").length,waiting:rows.filter(r=>r.status==="Awaiting Customer").length,escalated:rows.filter(r=>r.status==="Escalated"||(r.escalation_level&&r.escalation_level!=="None")).length,resolved:rows.filter(r=>r.status==="Resolved"&&isToday(r.created_at)).length}),[rows]);
 const hasFilters=Boolean(q||category!=="All"||status!=="All"||priority!=="All"||queue!=="All"||days!=="30");
 async function open(row:RequestRow){setSelected(row);setError("");setComment("");setMessage("");try{const [notes,thread]=await Promise.all([api<Comment[]>(`/service-requests/${row.id}/comments`),api<RequestMessage[]>(`/service-requests/${row.id}/messages`)]);setComments(notes);setMessages(thread)}catch(e:any){setError(e.message)}}
 async function changeStatus(next:string){if(!selected)return;setSaving(true);setError("");try{const updated=await api<RequestRow>(`/service-requests/${selected.id}`,{method:"PATCH",body:JSON.stringify({status:next})});setSelected(updated);setRows(items=>items.map(item=>item.id===updated.id?updated:item))}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 async function addComment(){if(!selected||!comment.trim())return;setSaving(true);setError("");try{const added=await api<Comment>(`/service-requests/${selected.id}/comments`,{method:"POST",body:JSON.stringify({comment})});setComments(items=>[...items,added]);setComment("")}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 async function sendMessage(){if(!selected||!message.trim())return;setSaving(true);setError("");try{const added=await api<RequestMessage>(`/service-requests/${selected.id}/messages`,{method:"POST",body:JSON.stringify({message})});setMessages(items=>[...items,added]);setMessage("")}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 function clearFilters(){setQ("");setCategory("All");setStatus("All");setPriority("All");setQueue("All");setDays("30")}
 return <div className="requests-page">
  <header className="requests-heading"><div><h1>Service requests</h1><p>Review requests, update progress, and record internal notes.</p></div><p className="requests-motto">People&nbsp;&nbsp; Progress&nbsp;&nbsp; Possibilities<i/></p></header>
  <section className="request-kpis"><Kpi icon={<FileText/>} value={stats.total} label="Total Requests" trend="↑ 20%" note="vs last 7 days" tone="blue"/><Kpi icon={<Clock3/>} value={stats.open} label="Open" trend="↑ 1" note="vs last 7 days" tone="purple"/><Kpi icon={<Clock3/>} value={stats.waiting} label="Awaiting Customer" trend="→ 0" note="vs last 7 days" tone="amber"/><Kpi icon={<ShieldAlert/>} value={stats.escalated} label="Escalated" trend="↑ 1" note="vs last 7 days" tone="red"/><Kpi icon={<FileText/>} value={stats.resolved} label="Resolved (Today)" trend="→ 0" note="vs last 7 days" tone="green"/></section>
  <section className="request-filters"><label className="request-search"><Search/><input aria-label="Search service requests" placeholder="Search by request number, customer name, issue or category..." value={q} onChange={e=>setQ(e.target.value)}/></label><Filter label="Category" value={category} options={options.categories} onChange={setCategory}/><Filter label="Status" value={status} options={options.statuses} onChange={setStatus}/><Filter label="Priority" value={priority} options={options.priorities} onChange={setPriority}/><Filter label="Assigned queue" value={queue} options={options.queues} onChange={setQueue}/><label className="request-date"><CalendarDays/><select aria-label="Date range" value={days} onChange={e=>setDays(e.target.value)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="All">All time</option></select><ChevronDown/></label><button className="clear-request-filters" disabled={!hasFilters} onClick={clearFilters}><RotateCcw/>Clear filters</button></section>
  <section className="request-table-card"><div className="request-table-scroll"><table className="request-table"><thead><tr><th>#</th><th>Request <ArrowDownUp/></th><th>Customer ID</th><th>Customer name</th><th>Category</th><th>Issue</th><th>Priority</th><th>Assigned queue</th><th>Status</th><th>Created on <ArrowDownUp/></th><th>Actions</th></tr></thead><tbody>{visible.map((row,index)=><tr key={row.id}><td>{(page-1)*PAGE_SIZE+index+1}</td><td className="request-code">{row.request_code}</td><td>{row.customer_code||row.customer_id}</td><td>{row.customer_name||"Unknown customer"}</td><td><Badge value={row.category} kind="category"/></td><td className="request-issue">{row.issue}</td><td><Badge value={row.priority} kind="priority"/></td><td className="request-queue">{row.assigned_queue||"Standard Queue"}</td><td><Badge value={row.status} kind="status"/></td><td className="request-date-cell">{formatDate(row.created_at)}</td><td><div className="request-actions"><button onClick={()=>open(row)}><MessageSquarePlus/>Manage</button><button aria-label={`More actions for ${row.request_code}`}><MoreVertical/></button></div></td></tr>)}</tbody></table>{!visible.length&&<p className="request-empty">No matching requests.</p>}</div><footer className="request-pagination"><span>Showing {filtered.length?Math.min((page-1)*PAGE_SIZE+1,filtered.length):0}–{Math.min(page*PAGE_SIZE,filtered.length)} of {filtered.length} requests</span><div><button aria-label="Previous page" disabled={page===1} onClick={()=>setPage(v=>v-1)}><ArrowLeft/></button><b>{page}</b><button aria-label="Next page" disabled={page===pageCount} onClick={()=>setPage(v=>v+1)}><ArrowRight/></button></div><label>Rows per page <select aria-label="Rows per page" value={PAGE_SIZE} disabled><option>{PAGE_SIZE}</option></select></label></footer></section>
  {selected&&<div className="service-request-overlay" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><section className="service-request-drawer"><div className="drawer-heading"><div><p>{selected.request_code}</p><h2>Manage service request</h2></div><button onClick={()=>setSelected(null)} aria-label="Close"><X/></button></div><div className="drawer-summary"><p>{selected.category} • Customer {selected.customer_code||selected.customer_id}</p><span>{selected.issue}</span><b>Priority: {selected.priority}</b></div><label className="drawer-status">Status<select className="input" value={selected.status} disabled={saving} onChange={e=>changeStatus(e.target.value)}>{statuses.map(item=><option key={item}>{item}</option>)}</select></label><DrawerSection title="Customer conversation" description="Messages here are visible to the customer." items={messages.map(item=>({id:item.id,text:item.message,meta:`${item.sender_name} • ${new Date(item.created_at).toLocaleString()}`,className:item.sender_type==="employee"?"employee-message":"customer-message"}))} empty="No customer-visible messages yet." value={message} setValue={setMessage} placeholder="Write a reply to the customer…" button="Send to customer" disabled={saving||!message.trim()} action={sendMessage}/><DrawerSection title="Internal comments" description="Visible to bank employees only." items={comments.map(item=>({id:item.id,text:item.comment,meta:`${item.author_name} • ${new Date(item.created_at).toLocaleString()}`,className:"internal-message"}))} empty="No internal comments yet." value={comment} setValue={setComment} placeholder="Add investigation notes, customer follow-up details, or resolution comments…" button="Add internal comment" disabled={saving||!comment.trim()} action={addComment} internal/>{error&&<p className="drawer-error">{error}</p>}</section></div>}
 </div>
}
function unique(values:string[]){return [...new Set(values.filter(Boolean))].sort()}
function isToday(value:string){const date=new Date(value),today=new Date();return date.toDateString()===today.toDateString()}
function formatDate(value:string){const date=new Date(value);return <>{date.toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"})}<br/>{date.toLocaleTimeString("en-US",{hour:"2-digit",minute:"2-digit"})}</>}
function Kpi({icon,value,label,trend,note,tone}:{icon:React.ReactNode;value:number;label:string;trend:string;note:string;tone:string}){return <article className={`request-kpi ${tone}`}><span>{icon}</span><div><strong>{value}</strong><b>{label}</b></div><aside><b>{trend}</b><small>{note}</small></aside></article>}
function Filter({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}){return <label className="request-filter"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}><option>All</option>{options.map(option=><option key={option}>{option}</option>)}</select><ChevronDown/></label>}
function Badge({value,kind}:{value:string;kind:string}){const key=value.toLowerCase().replaceAll(" ","-");return <span className={`request-badge ${kind}-${key}`}>{value}</span>}
function DrawerSection({title,description,items,empty,value,setValue,placeholder,button,disabled,action,internal=false}:{title:string;description:string;items:{id:number;text:string;meta:string;className:string}[];empty:string;value:string;setValue:(v:string)=>void;placeholder:string;button:string;disabled:boolean;action:()=>void;internal?:boolean}){return <div className={`drawer-section ${internal?"internal":""}`}><h3>{title}</h3><p>{description}</p><div className="drawer-thread">{items.map(item=><div key={item.id} className={item.className}><span>{item.text}</span><small>{item.meta}</small></div>)}{!items.length&&<p className="drawer-empty">{empty}</p>}</div><textarea className="input" maxLength={2000} placeholder={placeholder} value={value} onChange={e=>setValue(e.target.value)}/><button className="btn-primary" disabled={disabled} onClick={action}>{button}</button></div>}
