"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {ArrowRight,CheckCircle2,Clock3,MessageCircle,Search,Sparkles,X} from "lucide-react";
import {api} from "@/lib/api";
type Conversation={id:number;title:string;primary_intent:string;sentiment:string;resolution_status:string;summary?:string;created_at:string;updated_at:string};
type Detail=Conversation&{messages?:{id:number;role:string;content:string;created_at:string}[]};
const dateTime=(value:string)=>new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value));
const cleanSummary=(item:Conversation)=>item.summary?.replace(/Customer contacted the bank regarding /i,"").replace(/Current sentiment is neutral\.\s*/i,"").replace(/The interaction is awaiting confirmation that the customer is satisfied\.?/i,"").trim()||`Conversation about ${item.primary_intent.toLowerCase()}.`;
export default function Page(){
 const [items,setItems]=useState<Conversation[]>([]),[query,setQuery]=useState(""),[filter,setFilter]=useState("All"),[loading,setLoading]=useState(true),[selected,setSelected]=useState<Detail|null>(null),[detailLoading,setDetailLoading]=useState(false);
 useEffect(()=>{api<Conversation[]>("/conversations").then(setItems).finally(()=>setLoading(false))},[]);
 const filters=useMemo(()=>["All",...Array.from(new Set(items.map(item=>item.primary_intent)))],[items]);
 const visible=useMemo(()=>items.filter(item=>(filter==="All"||item.primary_intent===filter)&&`${item.title} ${item.primary_intent} ${item.summary||""}`.toLowerCase().includes(query.toLowerCase())),[items,query,filter]);
 async function open(item:Conversation){setDetailLoading(true);setSelected(item);try{setSelected(await api<Detail>(`/conversations/${item.id}`))}finally{setDetailLoading(false)}}
 return <div className="conversation-history">
  <header className="conversation-history-head"><div><p><i/> Conversations</p><h1>Your conversations</h1><span>Review your recent chats and continue whenever you need help.</span></div><div className="conversation-count"><MessageCircle/><span><b>{items.length}</b> conversations</span></div></header>
  <section className="conversation-tools"><label><Search/><input aria-label="Search conversations" placeholder="Search by topic or message" value={query} onChange={event=>setQuery(event.target.value)}/></label><div>{filters.slice(0,5).map(value=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{value}</button>)}</div></section>
  <section className="conversation-list">{loading?<div className="conversation-empty">Loading your conversations…</div>:visible.length?visible.map(item=><button key={item.id} className="conversation-row" onClick={()=>open(item)}><span className="conversation-row-icon"><MessageCircle/></span><span className="conversation-row-main"><span className="conversation-row-title"><b>{item.title||item.primary_intent}</b><time>{dateTime(item.updated_at||item.created_at)}</time></span><span className="conversation-row-summary">{cleanSummary(item)}</span><span className="conversation-row-tags"><i>{item.primary_intent}</i><i className={`sentiment ${item.sentiment.toLowerCase().replaceAll(" ","-")}`}>{item.sentiment}</i><i className="resolved"><CheckCircle2/>{item.resolution_status}</i></span></span><ArrowRight className="conversation-row-arrow"/></button>):<div className="conversation-empty"><Search/><h2>No conversations found</h2><p>Try another search or start a new conversation with the AI Assistant.</p></div>}</section>
  {selected&&<div className="conversation-drawer" role="dialog" aria-modal="true" aria-label="Conversation details"><button className="conversation-drawer-scrim" aria-label="Close" onClick={()=>setSelected(null)}/><article><header><div><p>{selected.primary_intent}</p><h2>{selected.title}</h2><span><Clock3/> {dateTime(selected.updated_at||selected.created_at)}</span></div><button aria-label="Close conversation details" onClick={()=>setSelected(null)}><X/></button></header><div className="conversation-transcript">{detailLoading?<p className="conversation-loading">Loading conversation…</p>:selected.messages?.length?selected.messages.map(message=><div key={message.id} className={message.role==="user"?"customer-message":"assistant-message"}><small>{message.role==="user"?"You":"Union Engage AI"}</small><p>{message.content}</p></div>):<div className="conversation-empty"><Sparkles/><p>No transcript is available for this conversation.</p></div>}</div><footer className="conversation-continue"><Link href={`/customer/chat?conversation=${selected.id}`}>Continue conversation <ArrowRight/></Link><p>Your previous messages will remain available as context.</p></footer></article></div>}
 </div>
}
