"use client";
import {useEffect,useState,use} from "react";
import {AlertTriangle,ArrowRight,HeartPulse} from "lucide-react";
import {CartesianGrid,Line,LineChart,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {api} from "@/lib/api";

export default function Page({params}:{params:Promise<{id:string}>}){
 const {id}=use(params),[d,setD]=useState<any>(),[history,setHistory]=useState<any>(),[error,setError]=useState("");
 useEffect(()=>{let active=true;const load=()=>api<any>(`/conversations/${id}`).then(detail=>{if(active)setD(detail);return api(`/customers/${detail.customer_id}/sentiment-history?limit=10`)}).then(value=>{if(active){setHistory(value);setError("")}}).catch((e:any)=>{if(active)setError(e.message)});void load();const timer=window.setInterval(()=>{if(document.visibilityState==="visible")void load()},5000);return()=>{active=false;window.clearInterval(timer)}},[id]);
 if(error)return <p className="text-red-600">{error}</p>;if(!d)return <p>Loading conversation…</p>;const insight=d.insights;
 return <><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold text-navy">Conversation #{id}</h1><p className="mt-2 max-w-3xl text-slate-500">{insight.conversation_summary}</p></div><span className={`badge ${insight.interaction_quality==="At Risk"?"bg-red-50 text-red-700":insight.interaction_quality==="Poor"?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700"}`}>{insight.interaction_quality}</span></div>
 <div className="mt-6 grid gap-5 xl:grid-cols-[1fr_390px]"><div className="space-y-5"><section className="card space-y-4 p-6">{d.messages.map((m:any)=><div key={m.id} className={`max-w-[80%] rounded-xl p-3 text-sm leading-6 ${m.role==="user"?"ml-auto bg-navy text-white":"bg-slate-100"}`}>{m.content}</div>)}</section><SentimentChart title="Selected session sentiment" subtitle="Up to the latest 10 customer messages in this session. Updates every 5 seconds." data={insight.sentiment_progression.slice(-10).map((item:any,index:number)=>({...item,label:`M${Math.max(1,insight.sentiment_progression.length-9)+index}`}))}/><SentimentChart title={`${history?.customer_name||"Customer"} — ${history?.shown_sessions||0} most recent session${history?.shown_sessions===1?"":"s"}`} subtitle={`Showing ${history?.shown_sessions||0} of ${history?.total_sessions||0} available sessions (maximum 10), oldest to newest.`} data={(history?.sessions||[]).map((item:any)=>({...item,label:`#${item.conversation_id}`}))}/><section className="card p-6"><h2 className="font-bold text-navy">Session sentiment sequence</h2><div className="mt-4 flex flex-wrap items-center gap-2">{insight.sentiment_progression.slice(-10).map((item:any,index:number)=><div className="flex items-center gap-2" key={index}><div className={`rounded-xl px-3 py-2 text-xs ${item.sentiment.includes("Negative")?"bg-red-50 text-red-700":"bg-slate-100"}`}><strong>{item.sentiment}</strong><span className="ml-1">• {item.emotion}</span></div>{index<Math.min(insight.sentiment_progression.length,10)-1&&<ArrowRight size={14} className="text-slate-300"/>}</div>)}</div></section></div>
 <aside className="space-y-4"><ExperienceScores sessions={history?.sessions||[]}/><Info title="Conversation summary" value={insight.conversation_summary}/><Info title="Customer issue" value={insight.customer_issue}/><div className="card p-5"><div className="flex items-center gap-2 font-bold text-navy"><HeartPulse className="text-brand" size={18}/>Interaction intelligence</div><dl className="mt-4 space-y-3 text-sm"><Metric label="Intent" value={insight.intent}/><Metric label="Sentiment" value={insight.sentiment}/><Metric label="Emotion" value={insight.emotion}/><Metric label="Resolution" value={insight.resolution_status}/><Metric label="Route" value={insight.recommended_route}/></dl></div><div className={`rounded-2xl border p-5 ${insight.engagement.eligible?"border-emerald-200 bg-emerald-50":"border-red-200 bg-red-50"}`}><p className="text-xs font-semibold uppercase tracking-wide">Engagement decision</p><h3 className="mt-1 font-bold">{insight.engagement.state}</h3><p className="mt-2 text-sm leading-6">{insight.engagement.action}</p><ul className="mt-3 list-disc space-y-1 pl-5 text-xs">{insight.engagement.reasons.map((reason:string)=><li key={reason}>{reason}</li>)}</ul></div><div className="card p-5"><h3 className="font-bold text-navy">Reason for dissatisfaction</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-slate-600">{insight.dissatisfaction_reasons.map((reason:string)=><li key={reason}>{reason}</li>)}</ul></div><Info title="Customer expectation" value={insight.customer_expectation}/><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex gap-2 font-bold text-amber-900"><AlertTriangle size={18}/>Suggested next action</div><p className="mt-2 text-sm leading-6 text-amber-800">{insight.suggested_next_action}</p></div></aside></div></>;
}
function Info({title,value}:{title:string;value:string}){return <div className="card p-5"><p className="text-xs text-slate-500">{title}</p><p className="mt-2 text-sm font-semibold leading-6">{value}</p></div>}
function Metric({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-slate-400">{label}</dt><dd className="font-semibold">{value}</dd></div>}
function ExperienceScores({sessions}:{sessions:any[]}){const scores=sessions.map(session=>session.csat??3),csat=scores.length?scores.reduce((sum,value)=>sum+value,0)/scores.length:3,defaults=sessions.filter(session=>session.csat==null).length;return <section className="card p-5"><h2 className="font-bold text-navy">Customer satisfaction</h2><div className="mt-4 rounded-xl bg-blue-50 p-4"><p className="text-xs font-medium text-blue-700">Average CSAT</p><p className="mt-1 text-2xl font-bold text-navy">{csat.toFixed(1)}<span className="text-sm font-medium text-slate-400">/5</span></p></div><p className="mt-3 text-xs leading-5 text-slate-500">Based on the latest {sessions.length||10} sessions. {defaults} session{defaults===1?"":"s"} without customer feedback use the neutral default CSAT of 3/5.</p></section>}
function SentimentChart({title,subtitle,data}:{title:string;subtitle:string;data:any[]}){return <section className="card p-6"><h2 className="font-bold text-navy">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p><div className="mt-4 h-64">{data.length?<ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{left:0,right:20,top:10,bottom:5}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis domain={[-1,1]} ticks={[-1,-.5,0,.5,1]}/><ReferenceLine y={0} stroke="#94a3b8"/><Tooltip content={({active,payload}:any)=>active&&payload?.length?<div className="max-w-sm rounded-xl border bg-white p-3 text-xs shadow-lg"><p className="font-bold">{payload[0].payload.title||payload[0].payload.intent||payload[0].payload.label}</p>{payload[0].payload.message&&<p className="mt-2 whitespace-normal leading-5 text-slate-600">“{payload[0].payload.message}”</p>}<p className="mt-2 font-semibold">{payload[0].payload.sentiment} • score {Number(payload[0].payload.score).toFixed(2)}</p><p className="mt-1 text-slate-500">{payload[0].payload.emotion}{payload[0].payload.interaction_count?` • ${payload[0].payload.interaction_count} interaction${payload[0].payload.interaction_count===1?"":"s"}`:""}</p>{payload[0].payload.updated_at&&<p className="mt-1 text-slate-400">{new Date(payload[0].payload.updated_at).toLocaleString()}</p>}</div>:null}/><Line type="monotone" dataKey="score" stroke="#d97706" strokeWidth={3} dot={{r:5}}/></LineChart></ResponsiveContainer>:<div className="grid h-full place-items-center text-sm text-slate-400">No sentiment history available.</div>}</div></section>}
