"use client";
import {useEffect,useState,use} from "react";
import {AlertTriangle,ArrowRight,HeartPulse} from "lucide-react";
import {api} from "@/lib/api";

export default function Page({params}:{params:Promise<{id:string}>}){
 const {id}=use(params),[d,setD]=useState<any>(),[error,setError]=useState("");
 useEffect(()=>{api(`/conversations/${id}`).then(setD).catch((e:any)=>setError(e.message))},[id]);
 if(error)return <p className="text-red-600">{error}</p>;if(!d)return <p>Loading conversation…</p>;const insight=d.insights;
 return <><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold text-navy">Conversation #{id}</h1><p className="mt-2 max-w-3xl text-slate-500">{insight.conversation_summary}</p></div><span className={`badge ${insight.interaction_quality==="At Risk"?"bg-red-50 text-red-700":insight.interaction_quality==="Poor"?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700"}`}>{insight.interaction_quality}</span></div>
 <div className="mt-6 grid gap-5 xl:grid-cols-[1fr_390px]"><div className="space-y-5"><section className="card space-y-4 p-6">{d.messages.map((m:any)=><div key={m.id} className={`max-w-[80%] rounded-xl p-3 text-sm leading-6 ${m.role==="user"?"ml-auto bg-navy text-white":"bg-slate-100"}`}>{m.content}</div>)}</section><section className="card p-6"><h2 className="font-bold text-navy">Sentiment progression</h2><div className="mt-4 flex flex-wrap items-center gap-2">{insight.sentiment_progression.map((item:any,index:number)=><div className="flex items-center gap-2" key={index}><div className={`rounded-xl px-3 py-2 text-xs ${item.sentiment.includes("Negative")?"bg-red-50 text-red-700":"bg-slate-100"}`}><strong>{item.sentiment}</strong><span className="ml-1">• {item.emotion}</span></div>{index<insight.sentiment_progression.length-1&&<ArrowRight size={14} className="text-slate-300"/>}</div>)}</div></section></div>
 <aside className="space-y-4"><Info title="Customer issue" value={insight.customer_issue}/><div className="card p-5"><div className="flex items-center gap-2 font-bold text-navy"><HeartPulse className="text-brand" size={18}/>Interaction intelligence</div><dl className="mt-4 space-y-3 text-sm"><Metric label="Intent" value={insight.intent}/><Metric label="Sentiment" value={insight.sentiment}/><Metric label="Emotion" value={insight.emotion}/><Metric label="Resolution" value={insight.resolution_status}/><Metric label="Route" value={insight.recommended_route}/></dl></div><div className="card p-5"><h3 className="font-bold text-navy">Reason for dissatisfaction</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-slate-600">{insight.dissatisfaction_reasons.map((reason:string)=><li key={reason}>{reason}</li>)}</ul></div><Info title="Customer expectation" value={insight.customer_expectation}/><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex gap-2 font-bold text-amber-900"><AlertTriangle size={18}/>Suggested next action</div><p className="mt-2 text-sm leading-6 text-amber-800">{insight.suggested_next_action}</p></div><div className="card p-5"><h3 className="font-bold text-navy">Customer feedback</h3>{insight.feedback?<div className="mt-3 grid grid-cols-2 gap-3"><Metric label="CSAT" value={`${insight.feedback.csat??"—"}/5`}/><Metric label="NPS" value={`${insight.feedback.nps??"—"}/10`}/></div>:<p className="mt-2 text-sm text-slate-500">Not submitted yet.</p>}</div></aside></div></>;
}
function Info({title,value}:{title:string;value:string}){return <div className="card p-5"><p className="text-xs text-slate-500">{title}</p><p className="mt-2 text-sm font-semibold leading-6">{value}</p></div>}
function Metric({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-slate-400">{label}</dt><dd className="font-semibold">{value}</dd></div>}
