from app.db.session import SessionLocal, engine
from app.db.base import Base
from app.models import *
from app.core.security import hash_password

CUSTOMERS=[("CUST001","Aarav Mehta","Privilege","Mumbai","2021",500000,180000,65000),("CUST002","Meera Nair","Classic","Kochi","2019",85000,95000,18000),("CUST003","Kabir Malhotra","Privilege","Delhi","2023",240000,150000,45000),("CUST004","Ishita Sen","Classic","Kolkata","2022",75000,85000,14000),("CUST005","Rohan Iyer","Classic","Bengaluru","2020",120000,70000,25000),("CUST006","Diya Kapoor","Classic","Pune","2024",65000,80000,16000),("CUST007","Vihaan Desai","Wealth","Ahmedabad","2017",900000,300000,110000),("CUST008","Saanvi Rao","Classic","Hyderabad","2018",40000,65000,7000),("CUST009","Arjun Bhat","Privilege","Chennai","2020",180000,125000,30000),("CUST010","Myra Joshi","Wealth","Jaipur","2016",750000,260000,90000)]
ARTICLES=[("Home loan documents","Loans","home,loan,documents,house","For a home-loan application, commonly required documents include identity and address proof, income documents such as salary slips and bank statements, employment proof, and property documents. Final requirements depend on applicant and property type."),("Block a debit card","Cards","debit,card,block,stolen,lost","You can immediately block a debit card through mobile or net banking under Card Controls, or contact the bank's 24-hour support line. Never share your PIN or OTP."),("Cheque book request","Accounts","cheque,book,order","You can request a cheque book through mobile banking, net banking, an ATM, or your branch. Delivery typically takes 5–7 business days."),("Fixed deposits","Deposits","fixed,deposit,fd,interest","Fixed deposits offer a fixed return for a selected tenure. Rates and premature withdrawal conditions vary; review the current schedule before booking."),("Digital banking help","Digital","net,mobile,banking,password,login","Use the Forgot Password option to restore digital banking access. The bank will verify your registered mobile number; never disclose an OTP."),("Account statements","Accounts","account,statement,transactions","Account statements can be downloaded from mobile or net banking by choosing the account and date range.")]
EXTRA_ARTICLES=[
 ("Minimum balance requirement","Accounts","minimum,balance,requirement,amb,average monthly balance,न्यूनतम बैलेंस","Minimum balance requirements depend on the savings-account variant. Customers should check the account details shown in mobile or net banking, or contact the branch for the requirement applicable to their account. Any penalty must be confirmed from the current approved schedule of charges."),
]
def upsert_articles(db):
 for title,category,keywords,content in ARTICLES+EXTRA_ARTICLES:
  article=db.query(KnowledgeArticle).filter_by(title=title).first()
  if article:
   article.category=category; article.keywords=keywords; article.content=content; article.active=True
  else: db.add(KnowledgeArticle(title=title,category=category,keywords=keywords,content=content))
def run():
 Base.metadata.create_all(engine); db=SessionLocal()
 try:
  if db.query(Customer).count():
   upsert_articles(db); db.commit(); return
  customers=[]
  for code,name,segment,city,since,balance,income,surplus in CUSTOMERS:
   c=Customer(customer_code=code,name=name,segment=segment,city=city,relationship_since=since,average_balance=balance,monthly_income=income,monthly_surplus=surplus); db.add(c); customers.append(c)
  db.flush(); password=hash_password("Demo@123")
  db.add(User(login_id="CUST001",password_hash=password,user_type="customer",role="customer",display_name=customers[0].name,customer_id=customers[0].id))
  for login,name,role in [("ADMIN001","Priya Sharma","admin"),("RM001","Ananya Rao","relationship_manager"),("SO001","Dev Khanna","service_officer"),("SALES001","Neel Shah","sales_officer")]: db.add(User(login_id=login,password_hash=password,user_type="employee",role=role,display_name=name))
  upsert_articles(db)
  for c,title,intent,sentiment,status in [(customers[1],"Repeated debit card complaint","Debit Card Complaint","Highly Negative","Unresolved"),(customers[2],"Planning a new home purchase","Home Loan Interest","Positive","In Progress"),(customers[7],"Considering account closure","Account Closure","Highly Negative","Unresolved")]: db.add(Conversation(customer_id=c.id,title=title,primary_intent=intent,sentiment=sentiment,resolution_status=status,summary=f"Customer interaction regarding {intent.lower()}."))
  db.flush()
  db.add_all([ServiceRequest(request_code="SR-2026-000124",customer_id=customers[1].id,conversation_id=1,category="Debit Card",issue="Card not working",priority="High",status="Open"),ServiceRequest(request_code="SR-2026-000125",customer_id=customers[8].id,category="Account",issue="Incorrect debit",priority="High",status="Escalated"),Lead(customer_id=customers[2].id,conversation_id=2,product="Home Loan",score=86,temperature="Hot",journey_stage="Eligibility",status="Qualified",next_action="RM callback",reasons=["Product intent explicitly expressed","Desired loan amount provided","Income disclosed","Timeline within 3 months"]),Lead(customer_id=customers[3].id,product="Home Loan",score=58,temperature="Warm",journey_stage="Income",status="Abandoned",next_action="Send reminder",reasons=["Journey 60% complete","Customer exited at eligibility stage"]),FinancialGoal(customer_id=customers[4].id,name="Car Goal",target_amount=500000,saved_amount=120000,timeline_months=24,monthly_required=15834),Opportunity(customer_id=customers[0].id,product="Fixed Deposit",score=88,reason="Sustained high average balance with no active term deposit",trigger="High idle balance",suggested_action="Explain suitable fixed-deposit tenure options"),Opportunity(customer_id=customers[6].id,product="FD Renewal",score=82,reason="Existing fixed deposit is approaching maturity",trigger="FD maturity in 30 days",suggested_action="Review maturity and renewal options"),RetentionScore(customer_id=customers[1].id,score=91,level="Critical",reasons=["Three unresolved complaints","Highly negative sentiment","CSAT 1/5","Repeat contact"],suggested_action="Priority RM intervention"),RetentionScore(customer_id=customers[7].id,score=88,level="Critical",reasons=["Account closure intent detected","Negative recent sentiment"],suggested_action="Senior service recovery call"),RoutingDecision(conversation_id=1,recommended_queue="Priority Service Queue",reason="Highly negative repeat contact"),RoutingDecision(conversation_id=3,recommended_queue="Supervisor Review",reason="Account closure intent with highly negative sentiment"),Notification(title="Critical attrition risk detected",severity="critical",customer_id=customers[1].id),Notification(title="Hot home-loan lead generated",severity="info",customer_id=customers[2].id),Notification(title="Customer abandoned loan qualification",severity="warning",customer_id=customers[3].id)])
  db.commit()
 finally: db.close()
if __name__=="__main__": run()
