"use client";
import {useState} from "react";
import {AlertTriangle,BookOpen,Mic,Paperclip,Send,ShieldCheck,Sparkles} from "lucide-react";
import {api} from "@/lib/api";

type Source={id:number;title:string;category:string;page?:number|null;source_type?:"pdf"|"article"};
type ChatMessage={role:"user"|"assistant";content:string;sources?:Source[];grounded?:boolean};
const languages=[["auto","Auto detect"],["en-IN","English"],["hi-IN","हिन्दी"],["bn-IN","বাংলা"],["gu-IN","ગુજરાતી"],["kn-IN","ಕನ್ನಡ"],["ml-IN","മലയാളം"],["mr-IN","मराठी"],["od-IN","ଓଡ଼ିଆ"],["pa-IN","ਪੰਜਾਬੀ"],["ta-IN","தமிழ்"],["te-IN","తెలుగు"]] as const;

export default function Page(){
 const [messages,setMessages]=useState<ChatMessage[]>([{role:"assistant",content:"Hello Aarav. I’m your Union Engage AI assistant. Choose your preferred language and ask me a banking question."}]);
 const [text,setText]=useState(""),[conversationId,setConversationId]=useState<number>(),[context,setContext]=useState<any>(null),[busy,setBusy]=useState(false),[created,setCreated]=useState(false),[language,setLanguage]=useState("auto"),[rating,setRating]=useState(false),[csat,setCsat]=useState<number>(),[nps,setNps]=useState<number>(),[feedbackSent,setFeedbackSent]=useState(false);
 async function send(value=text){
  if(!value.trim()||busy)return;
  setMessages(items=>[...items,{role:"user",content:value}]);setText("");setBusy(true);
  try{
   const result=await api<any>("/chat",{method:"POST",body:JSON.stringify({message:value,conversation_id:conversationId,language_code:language})});
   setConversationId(result.conversation_id);setContext(result);
   setMessages(items=>[...items,{role:"assistant",content:result.message,sources:result.knowledge_sources,grounded:result.grounded}]);
  }catch(error:any){setMessages(items=>[...items,{role:"assistant",content:`I couldn't connect to the banking service: ${error.message}`}])}
  finally{setBusy(false)}
 }
 async function raiseRequest(){const draft=context?.service_request_draft;if(!draft)return;await api("/service-requests",{method:"POST",body:JSON.stringify({conversation_id:conversationId,...draft})});setCreated(true)}
 async function submitFeedback(){if(!conversationId||csat===undefined||nps===undefined)return;await api("/feedback",{method:"POST",body:JSON.stringify({conversation_id:conversationId,csat,nps})});setFeedbackSent(true);setRating(false)}
 function voice(){const Recognition=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Recognition){alert("Voice input is not supported in this browser.");return}const recognition=new Recognition();recognition.lang=language==="auto"?"en-IN":language;recognition.onresult=(event:any)=>setText(event.results[0][0].transcript);recognition.start()}
 return <div className="grid h-[calc(100vh-4rem)] gap-5 lg:grid-cols-[1fr_310px]">
  <section className="card flex min-h-0 flex-col overflow-hidden">
   <header className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h1 className="text-xl font-bold text-navy">AI Banking Assistant</h1><p className="text-xs text-slate-500">Sarvam-powered • Grounded in approved bank knowledge • Never share PINs or OTPs</p></div><label className="text-xs font-medium text-slate-500">Response language<select aria-label="Response language" className="ml-2 rounded-lg border bg-white px-3 py-2 text-sm text-slate-700" value={language} onChange={event=>setLanguage(event.target.value)}>{languages.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label></header>
   <div className="flex-1 space-y-4 overflow-y-auto p-5">
    {messages.map((message,index)=><div key={index} className={`max-w-[82%] ${message.role==="user"?"ml-auto":""}`}><div className={`rounded-2xl px-4 py-3 text-sm leading-6 ${message.role==="user"?"bg-navy text-white":"bg-slate-100"}`}>{message.content}</div>{message.role==="assistant"&&message.grounded&&<div className="mt-1.5 flex flex-wrap items-center gap-1.5 px-2 text-[11px] text-slate-500"><ShieldCheck size={13} className="text-emerald-600"/>Grounded in approved knowledge{message.sources?.map(source=><span key={`${source.source_type}-${source.id}`} className="rounded bg-slate-100 px-1.5 py-0.5">{source.title}{source.page?` • p.${source.page}`:""}</span>)}</div>}</div>)}
    {context?.service_request_suggested&&!created&&<div className="max-w-lg rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><p className="font-semibold">Create a {context.service_request_draft?.category} service request?</p><p className="mt-1 text-xs text-slate-600">Priority: {context.service_request_draft?.priority} • You stay in control; nothing is submitted until you confirm.</p><div className="mt-3 flex gap-2"><button onClick={raiseRequest} className="btn-primary">Yes, raise request</button><button onClick={()=>setContext({...context,service_request_suggested:false})} className="btn-secondary">Not now</button></div></div>}
    {created&&<div className="badge bg-emerald-50 text-emerald-700">Service request created successfully</div>}{busy&&<div className="text-sm text-slate-400">Searching approved knowledge and preparing an answer…</div>}
   </div>
   <div className="border-t p-4"><div className="mb-3 flex gap-2 overflow-x-auto">{["What is the minimum balance requirement?","How can I block my debit card?","What documents are required for a home loan?","Mujhe cheque book order karni hai."].map(item=><button key={item} onClick={()=>send(item)} className="whitespace-nowrap rounded-full border px-3 py-1.5 text-xs hover:bg-slate-50">{item}</button>)}</div><div className="flex items-center gap-2"><button className="p-2 text-slate-400" aria-label="Attach file"><Paperclip size={19}/></button><button onClick={voice} className="p-2 text-slate-400" aria-label="Voice input"><Mic size={19}/></button><input className="input" placeholder="Ask a banking question in your preferred language…" value={text} onChange={event=>setText(event.target.value)} onKeyDown={event=>event.key==="Enter"&&send()}/><button onClick={()=>send()} className="btn-primary px-3" aria-label="Send"><Send size={18}/></button></div></div>
  </section>
  <aside className="space-y-4"><div className="card p-5"><div className="flex items-center gap-2 font-semibold"><Sparkles size={17} className="text-brand"/>Conversation context</div>{context?<div className="mt-4 space-y-3 text-sm"><Row label="Detected intent" value={context.analysis.intent}/><Row label="Response language" value={languages.find(([code])=>code===language)?.[1]||"Auto detect"}/><Row label="Knowledge status" value={context.grounded?"Approved source found":"No approved source found"}/>{context.knowledge_sources?.length>0&&<div><p className="text-xs text-slate-400">Retrieved sources</p>{context.knowledge_sources.map((source:Source)=><div key={`${source.source_type}-${source.id}`} className="mt-2 flex gap-2 rounded-lg bg-slate-50 p-2 text-xs"><BookOpen size={14}/><span>{source.title}<small className="block text-slate-400">{source.category}{source.page?` • Page ${source.page}`:""}</small></span></div>)}</div>}</div>:<p className="mt-4 text-sm text-slate-500">Intent and approved sources will appear as the conversation develops.</p>}</div>{conversationId&&!feedbackSent&&<div className="card p-5"><h3 className="font-semibold">How satisfied are you?</h3>{!rating?<button className="btn-secondary mt-3 w-full" onClick={()=>setRating(true)}>End & rate interaction</button>:<div className="mt-4 space-y-4"><div><p className="text-xs text-slate-500">CSAT</p><div className="mt-2 flex gap-1">{[1,2,3,4,5].map(value=><button key={value} onClick={()=>setCsat(value)} className={`h-8 w-8 rounded ${csat===value?"bg-navy text-white":"bg-slate-100"}`}>{value}</button>)}</div></div><label className="block text-xs text-slate-500">NPS (0–10)<select className="input mt-2" value={nps??""} onChange={e=>setNps(Number(e.target.value))}><option value="" disabled>Select score</option>{Array.from({length:11},(_,value)=><option key={value} value={value}>{value}</option>)}</select></label><button className="btn-primary w-full" disabled={csat===undefined||nps===undefined} onClick={submitFeedback}>Submit feedback</button></div>}</div>}{feedbackSent&&<div className="rounded-xl bg-emerald-50 p-4 text-sm font-medium text-emerald-700">Thank you for your feedback.</div>}<div className="rounded-xl border border-blue-100 bg-blue-50 p-4 text-xs text-blue-800"><AlertTriangle size={16} className="mb-2"/>Answers use approved demo knowledge. Confirm time-sensitive rates, fees, and eligibility with the bank.</div></aside>
 </div>
}
function Row({label,value}:{label:string;value:string}){return <div><p className="text-xs text-slate-400">{label}</p><p className="font-medium">{value}</p></div>}
