"use client";
import {useEffect,useRef,useState} from "react";
import {AlertTriangle,Mic,Send,ShieldCheck,Sparkles} from "lucide-react";
import {api} from "@/lib/api";

type Source={id:number;title:string;category:string;page?:number|null;source_type?:"pdf"|"article"};
type ChatMessage={role:"user"|"assistant";content:string;sources?:Source[];grounded?:boolean};
const languages=[["auto","Auto detect"],["en-IN","English"],["hi-IN","हिन्दी"],["bn-IN","বাংলা"],["gu-IN","ગુજરાતી"],["kn-IN","ಕನ್ನಡ"],["ml-IN","മലയാളം"],["mr-IN","मराठी"],["od-IN","ଓଡ଼ିଆ"],["pa-IN","ਪੰਜਾਬੀ"],["ta-IN","தமிழ்"],["te-IN","తెలుగు"]] as const;

export default function Page(){
 const [coachMode,setCoachMode]=useState(false);
 const [messages,setMessages]=useState<ChatMessage[]>([{role:"assistant",content:"Hello. I’m your AI banking assistant. I can explain banking services, answer questions, or help resolve an issue. How can I help?"}]);
 const [text,setText]=useState(""),[conversationId,setConversationId]=useState<number>(),[context,setContext]=useState<any>(null),[busy,setBusy]=useState(false),[created,setCreated]=useState(false),[language,setLanguage]=useState("auto"),[rating,setRating]=useState(false),[csat,setCsat]=useState<number>(),[feedbackSent,setFeedbackSent]=useState(false),[recording,setRecording]=useState(false),[transcribing,setTranscribing]=useState(false),[voiceError,setVoiceError]=useState("");
 const recorderRef=useRef<MediaRecorder|null>(null),streamRef=useRef<MediaStream|null>(null),timerRef=useRef<ReturnType<typeof setTimeout>|null>(null),recordingStartedRef=useRef(0);
 async function send(value=text){
  if(!value.trim()||busy)return;
  setMessages(items=>[...items,{role:"user",content:value}]);setText("");setBusy(true);
  try{
   const result=await api<any>("/chat",{method:"POST",body:JSON.stringify({message:value,conversation_id:conversationId,language_code:language})});
   setConversationId(result.conversation_id);setContext(result);
   setMessages(items=>[...items,{role:"assistant",content:result.message,sources:result.knowledge_sources,grounded:result.grounded}]);
  }catch(error:any){setMessages(items=>[...items,{role:"assistant",content:`I couldn't connect to the banking service: ${error.message}`}])}
  finally{setBusy(false)}
 }
 async function raiseRequest(){const draft=context?.service_request_draft;if(!draft)return;await api("/service-requests",{method:"POST",body:JSON.stringify({conversation_id:conversationId,...draft})});setCreated(true)}
 async function submitFeedback(){if(!conversationId||csat===undefined)return;await api("/feedback",{method:"POST",body:JSON.stringify({conversation_id:conversationId,csat})});setFeedbackSent(true);setRating(false)}
 async function saveAndExit(){if(context?.lead?.id)await api(`/leads/${context.lead.id}/abandon`,{method:"POST"});location.href="/customer/dashboard"}
 useEffect(()=>{const abandon=()=>{if(context?.lead?.id&&context.lead.status!=="Qualified")void api(`/leads/${context.lead.id}/abandon`,{method:"POST",keepalive:true})};window.addEventListener("pagehide",abandon);return()=>window.removeEventListener("pagehide",abandon)},[context?.lead?.id,context?.lead?.status]);
 function stopVoice(){if(recorderRef.current?.state==="recording"){recorderRef.current.requestData();recorderRef.current.stop()}}
 async function voice(){if(recording){stopVoice();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setVoiceError("Voice recording is not supported in this browser.");return}setVoiceError("");try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;const mimeType=MediaRecorder.isTypeSupported("audio/webm;codecs=opus")?"audio/webm;codecs=opus":"audio/webm";const recorder=new MediaRecorder(stream,{mimeType});const chunks:Blob[]=[];recorderRef.current=recorder;recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};recorder.onstop=async()=>{setRecording(false);stream.getTracks().forEach(track=>track.stop());streamRef.current=null;if(timerRef.current)clearTimeout(timerRef.current);if(Date.now()-recordingStartedRef.current<1000){setVoiceError("The recording was too short. Please speak for at least one second.");return}const audio=new Blob(chunks,{type:mimeType});if(!audio.size){setVoiceError("The browser produced an empty recording. Please try again.");return}setTranscribing(true);const form=new FormData();form.append("file",audio,"recording.webm");form.append("language_code",language);try{const result=await api<{transcript:string}>("/speech-to-text",{method:"POST",body:form});setText(result.transcript)}catch(error:any){setVoiceError(error.message)}finally{setTranscribing(false)}};recorder.start(250);recordingStartedRef.current=Date.now();setRecording(true);timerRef.current=setTimeout(()=>stopVoice(),29500)}catch(error:any){setVoiceError(error?.name==="NotAllowedError"?"Microphone permission was denied. Allow microphone access and try again.":"Unable to access the microphone.")}}
 useEffect(()=>()=>{if(timerRef.current)clearTimeout(timerRef.current);streamRef.current?.getTracks().forEach(track=>track.stop())},[]);
 useEffect(()=>{const params=new URLSearchParams(window.location.search),coaching=params.get("mode")==="coach",prompt=params.get("prompt"),vrm=params.get("topic")==="virtual-relationship-manager",resumeId=Number(params.get("conversation"));let name="Customer";try{name=JSON.parse(localStorage.getItem("user")||"{}").display_name?.split(" ")[0]||"Customer"}catch{}setCoachMode(coaching);if(resumeId){setBusy(true);api<any>(`/conversations/${resumeId}`).then(detail=>{setConversationId(detail.id);setMessages((detail.messages||[]).filter((item:any)=>item.role==="user"||item.role==="assistant").map((item:any)=>({role:item.role,content:item.content})));setContext(detail.analysis?.length?{analysis:detail.analysis[detail.analysis.length-1]}:null)}).catch((error:any)=>setMessages([{role:"assistant",content:`I couldn't reopen this conversation: ${error.message}`}])).finally(()=>setBusy(false));return}if(coaching)setMessages([{role:"assistant",content:`Hello ${name}. I’m your personalized financial coach. I’ll help you create a practical plan around your income, expenses, target, and timeline.`}]);else if(vrm)setMessages([{role:"assistant",content:`Hello ${name}. I’m your Virtual Relationship Manager. I can help with accounts, products, service needs, and connecting you with the right bank team. How may I assist?`}]);else setMessages([{role:"assistant",content:`Hello ${name}. I’m your AI banking assistant. I can explain banking services, answer questions, or help resolve an issue. How can I help?`}]);if(prompt)void send(prompt)},[]);
 return <div className="customer-chat-page grid h-[calc(100vh-4rem)] gap-5 lg:grid-cols-[1fr_310px]">
  <section className="chat-workspace card flex min-h-0 flex-col overflow-hidden">
   <header className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h1 className="text-xl font-bold text-navy">{coachMode?"Personalized Financial Coach":"AI Banking Assistant"}</h1><p className="text-xs text-slate-500">{coachMode?"Conversational financial planning":"Grounded assistance for your banking needs"} • Never share PINs or OTPs</p></div><label className="text-xs font-medium text-slate-500">Response language<select aria-label="Response language" className="ml-2 rounded-lg border bg-white px-3 py-2 text-sm text-slate-700" value={language} onChange={event=>setLanguage(event.target.value)}>{languages.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label></header>
   <div className="chat-messages flex-1 space-y-4 overflow-y-auto p-5">
    {messages.map((message,index)=><div key={index} className={`max-w-[82%] ${message.role==="user"?"ml-auto":""}`}><div className={`rounded-2xl px-4 py-3 text-sm leading-6 ${message.role==="user"?"bg-navy text-white":"bg-slate-100"}`}>{message.content}</div>{message.role==="assistant"&&message.grounded&&<div className="mt-1.5 flex items-center gap-1.5 px-2 text-[11px] text-slate-500"><ShieldCheck size={13} className="text-emerald-600"/>Verified with approved bank knowledge</div>}</div>)}
    {context?.goal&&<GoalCard goal={context.goal}/>} 
    {context?.service_request_suggested&&!created&&<div className="max-w-lg rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><p className="font-semibold">Create a {context.service_request_draft?.category} service request?</p><p className="mt-1 text-xs text-slate-600">Priority: {context.service_request_draft?.priority} • You stay in control; nothing is submitted until you confirm.</p><div className="mt-3 flex gap-2"><button onClick={raiseRequest} className="btn-primary">Yes, raise request</button><button onClick={()=>setContext({...context,service_request_suggested:false})} className="btn-secondary">Not now</button></div></div>}
    {created&&<div className="badge bg-emerald-50 text-emerald-700">Service request created successfully</div>}{busy&&<div className="text-sm text-slate-400">Searching approved knowledge and preparing an answer…</div>}
   </div>
   <div className="border-t p-4"><div className="flex items-center gap-2"><button onClick={voice} disabled={transcribing} className={`rounded-full p-2 ${recording?"animate-pulse bg-red-100 text-red-600":"text-slate-400 hover:bg-slate-100"}`} aria-label={recording?"Stop recording":"Start voice input"} title={recording?"Stop recording":"Record up to 30 seconds"}><Mic size={19}/></button><input className="input" placeholder={recording?"Listening… tap the microphone to stop":transcribing?"Converting voice to text…":"Ask a banking question in your preferred language…"} value={text} disabled={recording||transcribing} onChange={event=>setText(event.target.value)} onKeyDown={event=>event.key==="Enter"&&send()}/><button onClick={()=>send()} disabled={recording||transcribing} className="btn-primary px-3" aria-label="Send"><Send size={18}/></button></div>{voiceError&&<p className="mt-2 text-xs text-red-600" role="alert">{voiceError}</p>}{recording&&<p className="mt-2 text-xs text-red-600" role="status">Recording… tap the microphone to stop. Maximum 30 seconds.</p>}{transcribing&&<p className="mt-2 text-xs text-slate-500" role="status">Sarvam is converting your voice to text…</p>}</div>
  </section>
  <aside className="space-y-4"><div className="card p-5"><div className="flex items-center gap-2 font-semibold"><Sparkles size={17} className="text-brand"/>Conversation context</div>{context?<div className="mt-4 space-y-3 text-sm"><Row label="Detected intent" value={context.analysis.intent}/><Row label="Response language" value={languages.find(([code])=>code===language)?.[1]||"Auto detect"}/>{context.lead&&<div className="rounded-xl bg-blue-50 p-3"><p className="font-semibold text-blue-900">Home Loan <span className={`badge ml-1 ${context.lead.temperature==="Hot"?"bg-red-100 text-red-700":context.lead.temperature==="Warm"?"bg-amber-100 text-amber-700":"bg-blue-100 text-blue-700"}`}>{context.lead.temperature}</span></p><p className="mt-1 text-xs text-blue-700">Score {context.lead.score}/100 • Stage: {context.lead.stage}</p><div className="mt-2 h-1.5 rounded-full bg-blue-100"><div className="h-1.5 rounded-full bg-brand" style={{width:`${context.lead.score}%`}}/></div>{context.lead.status!=="Qualified"&&Object.keys(context.lead.collected||{}).length>0&&<button onClick={saveAndExit} className="mt-3 text-xs font-semibold text-blue-800 underline">Save and continue later</button>}</div>}</div>:<p className="mt-4 text-sm text-slate-500">Conversation details will appear as the discussion develops.</p>}</div>{conversationId&&!feedbackSent&&<div className="card p-5"><h3 className="font-semibold">How satisfied are you with this interaction?</h3>{!rating?<button className="btn-secondary mt-3 w-full" onClick={()=>setRating(true)}>End & rate interaction</button>:<div className="mt-4 space-y-4"><div><p className="text-xs text-slate-500">Choose one score from 1 (very dissatisfied) to 5 (very satisfied).</p><div className="mt-3 flex gap-2">{[1,2,3,4,5].map(value=><button key={value} aria-label={`Satisfaction ${value} out of 5`} onClick={()=>setCsat(value)} className={`h-10 w-10 rounded-lg ${csat===value?"bg-navy text-white":"bg-slate-100"}`}>{value}</button>)}</div></div><button className="btn-primary w-full" disabled={csat===undefined} onClick={submitFeedback}>Submit feedback</button></div>}</div>}{feedbackSent&&<div className="rounded-xl bg-emerald-50 p-4 text-sm font-medium text-emerald-700">Thank you for your feedback.</div>}<div className="rounded-xl border border-blue-100 bg-blue-50 p-4 text-xs text-blue-800"><AlertTriangle size={16} className="mb-2"/>Answers use approved demo knowledge. Confirm time-sensitive rates, fees, and eligibility with the bank.</div></aside>
 </div>
}
function Row({label,value}:{label:string;value:string}){return <div><p className="text-xs text-slate-400">{label}</p><p className="font-medium">{value}</p></div>}
function GoalCard({goal}:{goal:any}){
 const plan=goal.plan||{},inputs=plan.inputs||{};
 const money=(value:number|undefined)=>value?`₹${Number(value).toLocaleString("en-IN",{maximumFractionDigits:0})}`:"—";
 return <div className="max-w-2xl rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm">
  <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-emerald-700">Your coaching plan</p><h3 className="mt-1 font-bold text-navy">{goal.name}</h3></div><span className="badge bg-white text-emerald-700">{goal.status}</span></div>
  <div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Income" value={money(goal.monthly_income||inputs.monthly_income)}/><Metric label="Expenses" value={money(goal.monthly_expenses||inputs.monthly_expenses)}/><Metric label="Goal" value={money(goal.target_amount||inputs.target_amount)}/><Metric label="Timeline" value={(goal.timeline_months||inputs.timeline_months)?`${goal.timeline_months||inputs.timeline_months} months`:"—"}/></div>
  {goal.status==="Active"?<><div className="mt-3 rounded-xl bg-white p-3"><p className="font-semibold text-navy">{plan.feasible?"Your plan is achievable":"Your timeline needs adjustment"}</p><p className="mt-1 text-xs text-slate-600">Monthly surplus: {money(plan.monthly_surplus)} • Required: {money(plan.monthly_goal_required)} • Suggested contribution: {money(plan.recommended_monthly_contribution)}</p>{!plan.feasible&&plan.suggested_timeline_months&&<p className="mt-1 text-xs text-amber-700">Suggested timeline: about {plan.suggested_timeline_months} months</p>}</div>{plan.guidance?.length>0&&<ul className="mt-3 list-disc space-y-1 pl-5 text-xs text-slate-700">{plan.guidance.map((item:string)=><li key={item}>{item}</li>)}</ul>}</>:<p className="mt-3 text-xs font-medium text-emerald-800">Next: {goal.next_question}</p>}
 </div>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-white p-2"><p className="text-[10px] uppercase text-slate-400">{label}</p><p className="mt-0.5 font-semibold text-navy">{value}</p></div>}
