from pydantic_settings import BaseSettings, SettingsConfigDict

class Settings(BaseSettings):
    app_name: str = "Union Engage AI"
    database_url: str = "sqlite:///./union_engage.db"
    jwt_secret: str = "local-demo-secret"
    jwt_algorithm: str = "HS256"
    access_token_expire_minutes: int = 480
    ai_provider: str = "mock"
    sarvam_api_key: str = ""
    sarvam_base_url: str = "https://api.sarvam.ai"
    sarvam_chat_model: str = "sarvam-105b-conversations"
    sarvam_speech_model: str = "saaras:v3"
    sarvam_timeout_seconds: int = 90
    chat_reply_provider: str = "sarvam"
    local_chat_model: str = "gpt-oss:20b"
    local_chat_max_tokens: int = 550
    hf_chat_token: str = ""
    hf_chat_base_url: str = "https://router.huggingface.co/v1"
    hf_chat_model: str = "openai/gpt-oss-120b:cerebras"
    hf_chat_max_tokens: int = 550
    hf_chat_timeout_seconds: int = 90
    ollama_base_url: str = "http://localhost:11434"
    ollama_model: str = "llama3:latest"
    ollama_timeout_seconds: int = 90
    ollama_embedding_model: str = "bge-m3"
    ollama_embedding_timeout_seconds: int = 180
    local_sentiment_model: str = "cardiffnlp/twitter-roberta-base-sentiment-latest"
    local_sentiment_enabled: bool = True
    local_sentiment_local_files_only: bool = False
    local_translation_enabled: bool = True
    brevo_api_key: str = ""
    resend_api_key: str = ""
    resend_from_email: str = "onboarding@resend.dev"
    resend_from_name: str = "UNION-ENGAGE-AI"
    resend_timeout_seconds: int = 20
    smtp_from_email: str = ""
    smtp_from_name: str = "UNION-ENGAGE-AI"
    smtp_host: str = "smtp-relay.brevo.com"
    smtp_port: int = 587
    smtp_username: str = ""
    smtp_password: str = ""
    brevo_timeout_seconds: int = 20
    comfyui_base_url: str = "http://127.0.0.1:8188"
    comfyui_checkpoint: str = "flux1-schnell-fp8.safetensors"
    comfyui_timeout_seconds: int = 120
    cors_origins: str = "http://localhost:3000"
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")
settings = Settings()
